### ISSUE TITLE
'&' operator doesn't work on leftvalue

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#10]
Hello!
I'm trying to compile on windows some SDL based free software project which AFAIK compiles on Linux (supposedly with gcc) and I envetually step upon errors on this kind of expressions:
&--theEnemy->thinktime
&(theEnemy->dx -= 0.5)
&(++enemy[WC_BOSS].shield)
&(--engine.eventTimer)
&(star[i].x += (engine.ssx * star[i].speed))
And many others all alike. Although it is used in some kind optimisation hack, it seems to be valid code. The address-of operator is not limited to variable, but can be applied on any leftvalue. Or so it seems.

As '&' operator is hard to search for on the internet, the only clear reference to this behavior I could find is this: https://msdn.microsoft.com/en-us/library/64sa8b1e.aspx

**Comment by LADSoft** [comment]
Hi lionfaith!

well the argument of & is supposed to work on lvalues - and usually an 
lvalue is taken as something that can be assigned to (e.g. it is the 
left side of an assignment statement).   Other compilers such as the 
microsoft compiler, the borland compiler, and the watcom compiler all 
seem to stick to that definition; gcc is the only one I can find that 
has this other behavior.

However, that said, the GCC implementation doesn't seem to be out of 
bounds, because the latest spec actually defines an lvalue as something 
that can refer to an object, and I can see a case being made that the 
specific examples you have quoted do indeed refer to objects.   So I 
will look into implementing it :)

David

lionfaith wrote:

**Comment by LADSoft** [comment]
hi lionfaith,

I released a new version which will allow the compiler to take the address of objects that are returned from an assignment, a preincrement, or a postincrement.   Please let me know whether this is sufficient or if there are other types of expressions gcc lets get by as well.

David

**Comment by lionfaith** [comment]
Hi! Great thanks! So fast!
I've downloaded 5.25 and the faulty files now compiles without complains.
