### ISSUE TITLE
occ: very long running process for compilation of a single file (>270 seconds) with > 300-600MB RAM use

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#109]
When compiling [GnuCOBOL 3.0-rc1](https://sourceforge.net/projects/open-cobol/files/gnu-cobol/3.0/gnucobol-3.0-rc1_win.7z) the complete compilation takes less then 300 seconds.

More than 270 are used for a single file which seems way too much, even taking the relative big source file into account [> 900 KByte] (note: this source file is generated by Bison with a 355 KByte "original" source; a version of the Solaris C compiler and a very old DJGPP GCC have the same issue).

On most compilers this source needs less than 2 seconds to compile with full optimization.

Note: within 10 seconds the memory use of occ goes up to 314MB, staying there for 4 minutes then rasing up to 627MB within the last 30 seconds.

[parser.zip](https://github.com/LADSoft/OrangeC/files/1980522/parser.zip) containing only the main source file and its header (complete sources can be found at the link above).

**Comment by LADSoft** [comment]
yeah there are various problems where some files take extra time...   I definitely need to spend significant time on this issue but have let other things get ahead of it...   I have a redesign in mind that i think will take care of a lot of the worst cases.   I will look at this soon because 270 seconds is way too long...

**Comment by LADSoft** [comment]
The checkins above should address this issue as written, however, I'm leaving it open because there is an unrelated issue compiling oasm\x86parser.cpp that I may want to fix under the same umbrella...

**Comment by GitMensch** [comment]
Interestingly these changes also improve the CI build time from > 40 to < 38 minutes :-)

Shockingly the time needed to compile parser.c went down from > 270 seconds to less than 3!

**Comment by LADSoft** [comment]
yeah before I fixed anything I started checking around, and it turns out that many of the files in the build that I've historically been disgruntled with because I didn't like how long it took to compile them had this problem, just not anywhere near as pronounced.   Once I saw parser.c and the mruby problem I had something to work with in terms of something to fix...   I didn't expect the change to be quite that dramatic though...

When I first developed occ it was incredibly slow, I've actually spent a lot of time profiling it and making improvements.   It wasn't uncommon for even some relatively simple C language files to take 20-30 seconds to compile back in the beginning :).   I go back to it every now and then....

The linker is also much improved from what it was...   my first attempts at implementing virtual functions were really sluggish.

Next there is an issue where if you cram a lot of members into a class definition there is an exorbitant amount of time spent searching the class symbol table.   Fixing that might improve the CI build too, not sure...
