### ISSUE TITLE
access violation on runtime when calling function of external library

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#131]
~~~
oimplib.exe -! -C mpir.l mpir.dll
occ -! -o gmpver.exe gmpver.c -lmpir
gmpver.exe
gmpver.exe test
CS:EIP 0023:0040459F  SS:ESP 002B:0019ED50
EAX: 00000008  EBX: 00000000  ECX: 5B0C0CD0  EDX: 80808080  flags: 00010286
EBP: 0019FEE8  ESI: 5B0C0CD0  EDI: 00000000
 DS:     002B   ES:     002B   FS:     0053   GS:     002B
~~~

[bugme.zip](https://github.com/LADSoft/OrangeC/files/2012028/bugme.zip)

**Comment by LADSoft** [comment]
this actually is working as-designed.

First, for imports to work at all with that header file you apparently have to do:

#define __GMP_LIBGMP_DLL 1

before loading the gmp.h header.

Second, occ doesn't seem to support __declspec (I could have sworn I added that).   But it does currently support the same syntax the WATCOM compiler does if you want to move the defined() statement.

Make those two changes and it works fine...  but if you want to leave this open I will add __declspec over the weekend.

**Comment by GitMensch** [comment]
I see you've added declspec, but I'm confused with the "working as-designed" part. Shouldn't there be any RTL message instead of the access violation?

**Comment by LADSoft** [comment]
The RTL really has nothing to do with this... it is a matter of the compiler generating the 'correct' code to handle use-cases associated with a DLL import table.   Similarly if you pass a null to certain RTL functions you are also likely to get a crash...   because things are being done that are beyond the bounds of how it is specified to work.

When you set up the _import attribute properly the compiler generates an extra load instruction when referencing the data, to take into account the fact the data has to be dereferenced through the import table.    If the _import attribute isn't set the extra instruction doesn't get generated, and the behavior becomes undefined.

I was able to verify that the _import attribute wasn't set by the test program, which could easily lead to a crash since it is required to be used for DLL imports.   I was also able to verify that when it was set things worked as designed in terms of generating the proper instruction sequence and in terms of being functionally operational; so I closed this issue.
