### ISSUE TITLE
not right actual size for union type

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#16]
While debugging Project:Starfighter v1.1, I stepped upon a strange behaviour. Here is the faulty code. It's cpp file although anything from SDL is pure C. The bug appear with occ 5.36, but, if I'm correct, I'm struggling with it since 5.32. I have added the `printf( "DEBUG:..." )` and comments to show the behavior.

```C
engine.done = 0;
printf( "DEBUG: engine.done just after init: %d\n", engine.done );
/* engine.done is 0 */
flushInput();
printf( "DEBUG: engine.done after flushinput: %d\n", engine.done );
/* engine.done is -64 ! */
engine.keyState[SDLK_LCTRL] = engine.keyState[SDLK_RCTRL] = 0;

if ((currentGame.useMusic) && (engine.useAudio))
	Mix_PlayMusic(engine.music, 1);

while (!engine.done) /* breaks immediatly */
{
	gfx_updateScreen();
	gfx_unBuffer();

	now = SDL_GetTicks();

	doStarfield();
	doExplosions();
	etc...
}
```

Obviously, `flushInput()` is doing something wrong. It is a very simple function and here is his code:

```C
void flushInput()
{
	for (int i = 0 ; i < 350 ; i++)
		engine.keyState[i] = 0;

	while (SDL_PollEvent(&engine.event)){}
}
```

`flushInput` doesn't touch `engine.done` in any visible way! Possibility is that assigning to some field of `engine` is overflowing into neighbouring field. Here is the `done` field of `engine` and its nearest neighbor:
```C
typedef struct globalEngineVariables {

	SDL_Event event;
	signed char done;
	...
}
```

Most probably, when `SDL_PollEvent` do alter `engine.event`, it's also altering the `done` field. SDL_Event is a union. Could occ have a problem with unions?

I have tried to recude the code in a simpler form but could not reproduce the bug. I've tried a simple `sizeof( SDL_Event )` with occ and got `20`. As the SDL lib I use is compiled with msvc, I have made the same test with msvc (version shipped with windows SDK v7.1) and also got `20`. It was really disorienting: I can't reproduce it, I can't show evidence of it, still it's there.

So what's going wrong? I've then made an additional test: I've checked the value `&engine.done - &engine.event`. Occ warned it is unportable code but it worked and its value was `18`. Finally, an evidence of the bug (I hope it is)! It was really a hard one, I hope it will be easier for you.

Regards,
Lionel

**Comment by LADSoft** [comment]
Hi lionfaith,

you're right that is a hard one.  That is pretty good that you got that 
far, takes a certain talent for debugging.   But you were able to give 
me enough information to make a diagnosis of the problem, so thank you!

What is happening is orange C returns the sizeof value as if the 
structure were going to be used inside an array (to facilitate alignment 
in arrays) but otherwise uses the natural size of the structure for 
sizing.   In this case the aligned value is aligned to a multiple of 
four (20) whereas the natural size after applying the packing rules is 18.

Normally this isn't an issue as Orange C always uses the natural size 
except when reporting in a sizeof, however, what is happening is that 
when copying one instance of a structure to another, microsoft copies 
the full 20 bytes (as opposed to orange C only copying the 18) and that 
is where the problem lies... orange C only allocated 18 bytes!   So the 
microsoft code copies past the end of what Orange C allocated...

Well that sounds like a bug in Orange C, it should be allocating the 
full size as reported by sizeof() when a structure or union is located 
inside another structure or union.   I'll get it fixed within the next 
couple of days...

David

lionfaith wrote:

**Comment by lionfaith** [comment]
Hello, David!

It's just a problem with packing? Then I think you need to know this. Most SDL headers begins with `#include "begin_code.h"`. That begin_code.h contains the following code which manages struct packing so as to uniformise it throughout plateforms and compilers.

```C
/**
 *  @file begin_code.h
 *  Force structure packing at 4 byte alignment.
 *  This is necessary if the header is included in code which has structure
 *  packing set to an alternate value, say for loading structures from disk.
 *  The packing is reset to the previous value in close_code.h 
 */
#if defined(_MSC_VER) || defined(__MWERKS__) || defined(__BORLANDC__)
#ifdef _MSC_VER
#pragma warning(disable: 4103)
#endif
#ifdef __BORLANDC__
#pragma nopackwarning
#endif
#ifdef _M_X64
/* Use 8-byte alignment on 64-bit architectures, so pointers are aligned */
#pragma pack(push,8)
#else
#pragma pack(push,4)
#endif
#elif (defined(__MWERKS__) && defined(__MACOS__))
#pragma options align=mac68k4byte
#pragma enumsalwaysint on
#endif /* Compiler needs structure packing set */
```
It's not a problem for me if I have to modify it.


By the way, I had the following idea for a workaround the current bug. It worked pretty well.
```C
typedef struct globalEngineVariables {
    SDL_Event event;
    char event_spacer[2]; /* added this line */
    signed char done;
    ...
}
```

Regards,
Lionel

**Comment by LADSoft** [comment]
Hi Lionel,

well that is good to know!    The problem wasn't so much about proper 
packing, as padding the end of the structure to the next 4-byte 
boundary.   There's no control over the end of structure padding in 
Orange C, it just does it...   badly, apparently!

I'm glad you found a workaround, takes a little of the pressure to get a 
new version out off!   I'll let it sit for a couple of days in case 
there is anything else :)

David


lionfaith wrote:

**Comment by lionfaith** [comment]
Hello, David!

As I'm rather unexperienced with that kind of stuff, I've read a bit about padding and packing. And I came to make another test where I checked the offset of each field, field by bield.

```C
printf( "DEBUG: offset of key.type: %d\n", &engine.event.key.type - &engine.event );
printf( "DEBUG: offset of key.which: %d\n", &engine.event.key.which - &engine.event );
printf( "DEBUG: offset of key.state: %d\n", &engine.event.key.state - &engine.event );
printf( "DEBUG: offset of key.keysym: %d\n", &engine.event.key.keysym - &engine.event );
printf( "\n" );
printf( "DEBUG: offset of key.keysym.scancode: %d\n", &engine.event.key.keysym.scancode - &engine.event );
printf( "DEBUG: offset of key.keysym.sym: %d\n", &engine.event.key.keysym.sym - &engine.event );
printf( "DEBUG: offset of key.keysym.mod: %d\n", &engine.event.key.keysym.mod - &engine.event );
printf( "DEBUG: offset of key.keysym.unicode: %d\n", &engine.event.key.keysym.unicode - &engine.event );
```

And it gives:
```
DEBUG: offset of key.type: 0
DEBUG: offset of key.which: 1
DEBUG: offset of key.state: 2
DEBUG: offset of key.keysym: 0

DEBUG: offset of key.keysym.scancode: 4
DEBUG: offset of key.keysym.sym: 2
DEBUG: offset of key.keysym.mod: 3
DEBUG: offset of key.keysym.unicode: 8
```

Which is clearly inconsistent. And it's really confusing how starfighter could work with this data layout.

For your convenience, here are the definitions of these structures.

`SDL_Event`, as defined in `SDL_events.h` is a bit complex:
```C
typedef union SDL_Event {
	Uint8 type;
	SDL_ActiveEvent active;
	SDL_KeyboardEvent key;
	...
} SDL_Event;
```

`SDL_KeyboardEvent`, as defined in `SDL_events.h` is the biggest possible type for `SDL_Event`. And here is its definition:
```C
/** Keyboard event structure */
typedef struct SDL_KeyboardEvent {
	Uint8 type;	/**< SDL_KEYDOWN or SDL_KEYUP */
	Uint8 which;	/**< The keyboard device index */
	Uint8 state;	/**< SDL_PRESSED or SDL_RELEASED */
	SDL_keysym keysym;
} SDL_KeyboardEvent;
```

`SDL_keysym` itself is defined in `SDL_keyboard.h` and here it is:
```C
typedef struct SDL_keysym {
	Uint8 scancode;			/**< hardware specific scancode */
	SDLKey sym;			/**< SDL virtual keysym */
	SDLMod mod;			/**< current key modifiers */
	Uint16 unicode;			/**< translated character */
} SDL_keysym;
```

`SDLKey` and `SDLMod` are enum types and their definitions can be found in 
from SDL_keysym.h
```C
typedef enum {
        /** @name ASCII mapped keysyms
         *  The keyboard syms have been cleverly chosen to map to ASCII
         */
        /*@{*/
	SDLK_UNKNOWN		= 0,
	SDLK_FIRST		= 0,
	SDLK_BACKSPACE		= 8,
	...
	SDLK_UNDO		= 322,		/**< Atari keyboard has Undo */
        /*@}*/

	/* Add any other keys here */

	SDLK_LAST
} SDLKey;

/** Enumeration of valid key mods (possibly OR'd together) */
typedef enum {
	KMOD_NONE  = 0x0000,
	KMOD_LSHIFT= 0x0001,
	KMOD_RSHIFT= 0x0002,
	KMOD_LCTRL = 0x0040,
	KMOD_RCTRL = 0x0080,
	KMOD_LALT  = 0x0100,
	KMOD_RALT  = 0x0200,
	KMOD_LMETA = 0x0400,
	KMOD_RMETA = 0x0800,
	KMOD_NUM   = 0x1000,
	KMOD_CAPS  = 0x2000,
	KMOD_MODE  = 0x4000,
	KMOD_RESERVED = 0x8000
} SDLMod;
```

I hope it helps because it is really confusing me.

Regards,
Lionel

**Comment by LADSoft** [comment]
Hi Lionel,

I'm sorry for the delay here, I'm not sure what happened because I answered this when you wrote it.

Basically, when you do a subtraction of two pointer types, it returns the number of OBJECTS, not the number of BYTES.   When the pointers are char * or unsigned char * the size of an object is a byte so it is transparent, but when the pointer is a pointer to a larger type of integer or a structured type, the returned value is calculated by taking the difference between the pointers in bytes, and dividing by the size of the object.   So in the following:

int myInt[20];
int *one = &myInt[0];
int *two = &myInt[10];

diff = two - one;

the value of 'diff' is 10, whereas the offset in bytes between one and two is 40. (assuming sizeof(int) == 4)

In your example, the differences that are returning zero are structures...

This is pretty much the first thing that confused me about the C language, it really threw me for a loop when I realized what was going on :)

I've put up a new version of the compiler that fixes your original issue...

David

**Comment by lionfaith** [comment]
Hello, David!
Ok, I understand now. I've casted the `&` expressions with `(char*)` and occ stopped complaining about non portable code, and the output was finally coherent.

I have downloaded occ5.38, undo my workarounds, recompiled and it worked.

Don't worry about the delay, I've put it into use for other projects and activities.

Regard,
Lionel
