### ISSUE TITLE
function without arguments warned as being without a prototype

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#17]
Hello!
I step upon this bug while coding recenly with OCC5.50. I have reduced it down to the following. Hope it helps.

```C
#include <stdio.h>

char c;


#ifdef EMPTY
	void empty_func() {
		c = 'r';
	}
#else
	void empty_func(char d) {
		c = d;
	}
#endif

int main( int argc, char** argv ) {
	c = 'd';

#ifdef EMPTY 
	empty_func();
//output on compilation:
//Warning  test_bug.c(20):  Call to function 'empty_func' without a prototype in function main
#else
	empty_func( 'r' );
//no warning here
#endif

	putchar( c );
	return 0;
}
```

**Comment by lionfaith** [comment]
Note that putting `void` for the arguments removes the warning. That is `void empty_func(void)` instead of `void empty_func()`.

**Comment by bencz** [comment]
Hi @lionfaith!
I send a pull request to David, to solve this problem, take a look in pull #18

**Comment by LADSoft** [comment]
Hi Lionfaith,

yes that is expected, emptyfunc() is different from emptyfunc(void) in 
the C language (because the former actually allows you to put any number 
of arguments in the call whereas the latter allows you to put none).   
The disparity between those is part of the reason for the warning.

In C++ that was changed so that the two prototypes are equivalent.

Bencz's change fixes the problem but I think it has unintended side 
effects.   It may not properly issue errors if the argument types don't 
match the parameter types.

After some playing around with mingw32-cc I decided to leave the warning 
but demote it to a 'trivial' warning so it won't show up unless you ask 
for it.

I will have a new release within the next couple of days.

David



lionfaith wrote:

**Comment by lionfaith** [comment]
Hi David,
thanks for your nice answer with my mistake.

C is confusing and even experienced programmer makes the mistake as I could read on stackoverflow. I just tested the same code on [this online compiler] (http://gcc.godbolt.org/) with Clang and Gcc. And [here] (http://webcompiler.cloudapp.net/) I could test with msvc. Apparently, none of them complains about empty_func().

Thanks to you @bencz for your quick response.
