### ISSUE TITLE
_setmode with _O_BINARY doesn't work (\n is translated to \r\n)

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#203]
To get reproducible error / warning messages GnuCOBOL does

```c
		(void)_setmode (_fileno (stdin), _O_BINARY);
		(void)_setmode (_fileno (stdout), _O_BINARY);
		(void)_setmode (_fileno (stderr), _O_BINARY);
```

and a sample output of

```c
		  fprintf (stderr, _("%s: unrecognized option '--%s'"),
			   argv[0], "thisoptiondoesntexist");
		  fputc ('\n', stderr);
```

Leads to the line ending with hex "0d0a" instead of the expected hex "0a" (this "obviously" leads to many failures in the GnuCOBOL testsuite).

**Comment by GitMensch** [comment]
Note:

```c
fputs("test message", stderr);		// all fine, only hex 0a
fprintf(stderr,"test message"); fputc ('\n', stderr);	// bad: hex 0d0a
```

**Comment by LADSoft** [comment]
I can't immediatly duplicate.   What does the macro '_' do?

**Comment by LADSoft** [comment]
the O_BINARY flag testing seems solid...   I did some looking and it looks like if you use fcntl with F_SETFL it could reset the binary flag (which I will fix)...   any chance that could be happening?

**Comment by GitMensch** [comment]
> I can't immediately duplicate.

I have this reproducible when running the GnuCOBOL test suite. If you can't reproduce it I'd either have to try to setup a minimal example or (much better for me ;-) tell you how you can see this when running GnuCOBOL in the IDE via Debugger. Should be enough, shouldn't it?

> What does the macro '_' do?

In the case of the project, header and library files provided with #168: nothing. It is a common macro for gettext invocations - if the project isn't build with gettext support (which is the case in the provided files) it just evaluates to its content: `_("translatable string")` -> `"translatable string".

> I did some looking and it looks like if you use fcntl with F_SETFL it could reset the binary flag (which I will fix)... any chance that could be happening?

I don't think this is done directly and it doesn't happen on all places. Can a flush have something to do with it?

**Comment by LADSoft** [comment]
if you could tell me how to see this it would be appreciated.   I played with it a little while but don't know enough about COBC to be able to figure out how to get the program into the mode you are talking about...

**Comment by GitMensch** [comment]
@LADSoft I've just did a compare of an easy test, running (from cmd.exe)

`cobc.exe notthere.cob 2>err.log"

result with VS builds:

~~~
cobc: notthere.cob: No such file or directory

~~~

result with OrangeC builds:

~~~
cobc: notthere.cob: No such file or directory


~~~

There is a \r\n too much in.
Can you reproduce and debug this one?

**Comment by GitMensch** [comment]
... and the test for the initial bug report (most simple one as it only has one line):

1 set environment var (see #212 ;-) : `COB_UNIX_LF=YES`
2 run `cobc.exe` with the parameters `-q --thisoptiondoesntexist prog.cob`

expected output: file with a single 0x0a in (using the same codebase and a build from cl.exe [and all other win32 compilers I've checked so far] produce this), result: file with a single 0x0d0a. Note: switching between `COB_UNIX_LF=YES` and `COB_UNIX_LF=NO` should result in a different line ending.

**Comment by LADSoft** [comment]
i'm mostly taking the night off but wanted to make some progress on this one...   I can observe the problem but when I run a debugger on the cobc.exe executable with this argument I can't get it to break in the 'setmode' function.   I am used to using map files to debug without debugging info and I'm sure I got the breakpoint set right.

I did something similar last night, running cobc without any input file and observed the same problem...   at least it called the setmode function (however only once not three times) but the argument it gave was O_TEXT.

Of course without the setmode call it comes down to the \r\n behavior...

I will see if I can pin it down further tomorrow...

**Comment by GitMensch** [comment]
I'll recheck but setting the environment variable didn't worked in all places and in some other places there was just a line break too much...

**Comment by LADSoft** [comment]
hm...   I don't think we discussed the environment variable so I thought it might be overlooked.   I'll check it out some more later on...

**Comment by LADSoft** [comment]
I looked again and *now* my problem with this seems to be that it didn't work if I didn't work if I did it from msys, but works fine from cmd.exe.   I looked into it and simply setting COB_UNIX_LF from  msys isn't enough, the variable has to  be exported.   Once I exported the variable it started working...

please confirm that you exported the variable then I will look some more...

**Comment by GitMensch** [comment]
Variable exported from MSYS.

Can you reproduce one or both issues using the cobc commands in the first posts?

**Comment by GitMensch** [comment]
I've rechecked it using CI build 1.0.458, rebuild all within OCIDE. The two most simple checks have still the same issues:

```cmd
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>set COB_UNIX_LF=NO
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>cobc.exe '--thisoptiondoesntexist' 2>win.err
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>set COB_UNIX_LF=YES
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>cobc.exe '--thisoptiondoesntexist' 2>unix.err
```

Result: both error streams use 0x0d0a

```cmd
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>set COB_UNIX_LF=NO
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>cobc.exe nothere.cob 2>win.err
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>set COB_UNIX_LF=YES
C:\dev\gnucobol\build_windows\ocide\WIN32\Release>cobc.exe nothere.cob 2>unix.err
```

Result: both error streams use the correct line break, but both have a line break too much (when compared with GCC/MSVC builds)

**Comment by LADSoft** [comment]
I'm seeing the multiple line feeds from some of your examples, but still cannot duplicate the extra '\r'.   Will look at the LF problem in the hopes the two are somehow related :)

**Comment by LADSoft** [comment]
It finally happened...   it happened on the IDE-derived version.    I couldn't get it to happen in the version built with omake, which is what I have been testing with...

I think it happens because the DLL and EXE have different instances of the runtime and setting the mode in one doesn't set it in the other...   but the mode is being set in cobc.exe whereas the error message originates from libcob.dll.   OTOH in the omake version everything is in one executable and there is only one instance of the runtime.   

I will look at it further tomorrow...

**Comment by LADSoft** [comment]
I verified that under the same conditions, programs generated by the microsoft compilers act the same way, .e.g if you set the mode in the main program it is not reflected in the DLL, because there are two separate versions of the runtime and they don't communicate.   

Thing is, out of the box the microsoft compilers nowadays use a version of the runtime which is itself a DLL, so if you were compiling with the default settings on a microsoft compiler you wouldn't run into this issue.   Because if the runtime is in a DLL it can be shared by both the main program and any DLLs the program loads.   E.G we are back to only one instance of the runtime.   

So in the case of gnucobol you only see this issue on the microsoft compilers if you replace the runtime DLL with static librarys.

The 'easy' solution to this if you want to keep using DLLs is compile gnucobol against one of the various runtime DLLs orangec can use...   unfortunately that seems broken.    Works fine for regular apps but not DLLs sigh  (I'm about to look into why).    Another solution is forego the use of DLLs.   Another solution is put the test for COB_UNIX_LF in libcob.dll as well...

But I haven't forgotten the extra line feed at this point...

**Comment by LADSoft** [comment]
strerror was adding an extra line feed to error messages...

**Comment by LADSoft** [comment]
so at this point as i see it the problem is likely an issue with having multiple instances of the runtime that don't communicate.   Multiple runtimes aren't supposed to communicate though as far as I know, so it is a non-issue.   I've fixed LSCRTL.DLL if you want to try using that as the runtime and see what your mileage is :)

**Comment by GitMensch** [comment]
@LADSoft - I've fixed the missing setting of binary mode (and setting of textdomain if gettext is active) withing GnuCOBOL and 2 failures were gone. 368a00e fixed 3-6 other failures, even more were fixed by the sprintf parts.

In any case I'll switch to not statically link the runtime into the binaries (which is useful alone because of the size issue, much more as re-testing after a fix won't necessarily mean recompilation needed).

Closing this one :-)
