### ISSUE TITLE
Using occ with Csmith

### ISSUE THREAD

**Issue by ysangkok** [LADSoft/OrangeC#22]
I compiled Csmith in Cygwin and tried to use it with occ like this:

```
$ csmith --seed 0 --output test.c; occ /9 /Icsmith\\runtime test.c csmith\\runtime\\volatile_runtime.c
occ Version 5.62.0.1 Copyright (C) LADSoft 2006-2016

test.c
2 Diagnostics
csmith\runtime\volatile_runtime.c
olink Version 5.62.0.1 Copyright (C) LADSoft 2006-2016
Error: Invalid object file in line 11519 in test.o
Error: Undefined External main in module .\c0xpe.nas
        2 Errors, 0 Warnings
        Errors encountered, not creating output file
```

What could be the issue? Am I invoking this incorrectly? The line of test.o is `LR(R0,0,+,4).`

**Comment by LADSoft** [comment]
Hi Janus,

the 'invalid object file' message pretty much always means there is a 
bug in the compiler.   I will have to get csmith running again so I can 
get the test program and diagnose it...   it will possibly take me a 
couple of days.

David

Janus Troelsen wrote:

**Comment by LADSoft** [comment]
Hi Janus,

I compiled Csmith with visual studio and couldn't see the problem with 
the invalid object file.

The other problem, with 'main', is because nothing in Csmith runtime 
defines 'main'.   You would have to define it yourself. Whether you 
would want to or not I don't know...

But the invalid object file is a real problem.   I might not be seeing 
it for a variety of reasons.   I'm wondering, what version of CSmith are 
you using?   What version of Cygwin?   Also there is a possibility of 
some difference in the M4 processor used to create some of the runtime 
files.   So what version of M4 are you using?   I don't know much about 
M4, do you know if there is some configuration you might have in cygwin 
that I don't have, which might effect the issue?

Thanks,

David
Janus Troelsen wrote:

**Comment by ysangkok** [comment]
Hi David,

I am using Csmith from master. I am on Windows 10 64-bit. Cygwin is also 64-bit. I can tell you the GNU M4 version later, but it was the standard one from Cygwin.

But you shouldn't need Csmith to reproduce the issue. I can just send you the full test.c file and Csmith runtime when I am home.

**Comment by ysangkok** [comment]
I am using GNU M4 1.4.17-2 and GCC 5.3.0. Cygwin is version 2.3.1(0.291/5/3). Here are volatile_runtime.c and csmith.h and test.c: https://gist.github.com/ysangkok/b3ceb35300b7c95a33ae

**Comment by LADSoft** [comment]
Hi Janus,

for some reason my version of csmith didn't properly generate an output 
file for seed = 0.   I was able to replicate the problem easily when you 
gave me the test.c, even with my version of the csmith runtime.

There are a couple of problems with promoting 'static const int' 
declarations into real data which I am working on.   For anyone who 
doesn't know, 'static const int' variables are generally used inline and 
don't appear in the data segment, unless you take their address...   
which is where the problem comes in.   My support for that is slightly 
buggy.

Thanks for reporting this!

David

Janus Troelsen wrote:

**Comment by LADSoft** [comment]
Hi Janus,

I pushed fixes for your three existing problems to GIT; however further 
evaluation of various csmith output leaves me wanting to make further 
changes.    Specifically, there are problems with the huge 'main' 
functions in some of these files running the compiler out of memory (my 
inlining implementation causes an explosion of allocations in the 
optimizer), and I've isolated another problem where the compiler spends 
an inordinate amount of time trying to optimize hugely complex 
expressions, and another problem where the optimizer seems to get into 
an infinite loop.

I am working on it and will have another formal release when I get some 
of these things worked out.

David
Janus Troelsen wrote:

**Comment by LADSoft** [comment]
Hi Janus,

I've checked in a version which seems better now.  I ran 
csmith-generated code through orangec for about an hour and after 
performing several fixes the only problem  I'm seeing at this point is 
that some of the programs cmsith generates can take overly long to 
compile...

It will be a couple of days before I can make a formal release as I'm 
trying to help someone out with IDE problems.

David

Janus Troelsen wrote:

**Comment by ysangkok** [comment]
Thanks, David! Seems to work great now.

**Comment by LADSoft** [comment]
I worked on the speed issues recently and made significant headway, however, cannot presently release because the compiler won't reliably compile itself.
