### ISSUE TITLE
Switching to LSCRT.DLL (instead of statically link) leads to broken crt functions

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#225]
I've switched from statically linked runtime to LSCRT.DLL (via IDE, build commands changed from `/Wd` / `/Wc` to `/Wdl` / `/Wcl`) for the project files presented in #168 .

Starting cobc in the debugger using parameter `-fsyntax-only -t prog.lst -std=ibm prog.cob` now results in:

~~~
configuration error:
ibm-stri t. onf: No such file or directory
C:\dev\gnucobol\config\ibm.conf:22: configuration file was included here
~~~

The "obvious" error here is that a "c" is missing within the source file - this *only* happens when using LSCRT.DLL !?!

Another one seen when starting cobcrun in the debugger with the parameter `testfunc`:

```c
isdigit ((unsigned char)*ptr)
```

returns 0 for the ptr pointing to "0".

Please: Add a set of the compilations/tests in the CI build that use `/Wcl` / `/Wdl`, too (a good test may be be: change the *first* compilation of OrangeC with OrangeC to use DLLs instead of static linking the runtime). Afterwards the bug will likely be fixed :-)

Thinking more about this: Shouldn't two additional compilation runs be added to CI to actually test all possible CRT linking options?

Workaround: only use static linking of the runtime for now...

**Comment by LADSoft** [comment]
i couldn't duplicate the first problem but based on your observation about the second one it seems likely both are the same thing; e.g. the ctype functions are broken in lscrtl.dll.   That will be fixed soon.

As far as building the platform with dynamic dll, it can't be done for now because the dynamic DLL doesn't support C++.   HOWEVER, #223 is supposed to lay the groundwork for fixing that problem so it may be possible in the not-too-distant future

**Comment by GitMensch** [comment]
Rechecked this, the test results in the GnuCOBOL testsuite are identical no matter if compiled against LSCRT.DLL or static (25/902 failures, some only because of binary mode because of static linking in the generated modules).
