### ISSUE TITLE
Compiler rewrite to compile in C++ mode

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#235]
Making the change of compiling the compiler in C++ mode would allow the gradual replacement of duplicate code with various C++ libraries used by other tools in the package, and overall modernize the code base.

**Comment by chuggafan** [comment]
I think I'm going to begin work on this, as I noticed when attempting to work on #243 that there is no maximum recursion depth for constant expression checking, and I plan on adding it (and adding an option for it), so to be able to properly do that I'd have to make major modifications to the compiler, so when doing that I think I'll be slowly but surely moving things such as the lexer to a class based system. I'll take doing this slow, because it will take some time to do it (probably 6 months to a year), but I hope to be able to accomplish this task.

**Comment by chuggafan** [comment]
I will hopefully be able to get to that, but I fear that this rewrite I'm doing will be the maximum annoying thing, as I'm going to first (essentially) copy over the lexer to c++ classes. My current plan is to have the lexer have the settings passed into it, and a set of keywords, then take those two and (ab)use them as much as possible. I hope to have a skeleton of changes sometime in the next week (at least for the lexer, hopefully) so that you might be able to look over it and see what would need to change. I also hope that the rewrite I am doing would allow for more backends to be added (at least easier) and hopefully allow the integration of sanitizers a la clang and gcc (ASan, UBSan, etc.), but that's getting ahead of myself. I'll try to keep posted on what I'm doing while I'm doing it.

**Comment by chuggafan** [comment]
Ok, so I've gotten around to making a skeleton of a rewrite (specifically I've implemented the very basics of a Lexer, and the Errror system, and some skeleton Keyword class), I've put it up [here](https://github.com/chuggafan/OrangeC/blob/compilerrewrite/src/occRewrite) (ignore the fact that I partitioned it from my own master branch, I messed up on that part and I have no idea how to easily fix that...) But I'd like you to evaluate where I'm going with this, as it should be a good skeleton for what I'm thinking of (AKA: abstracting away keywords, allowing for more errors to be added, I want to be able to make the generation of code something that can be more abstracted as well, which means that some form of IR must be used, I'm not sure what, and I'd assume you would have much better experience with that than I would. Thank you for all the hard work! I hope to be able to actually help you with the major undertaking of a rewrite like this.

**Comment by LADSoft** [comment]
sorry i couldn't get on last night; storms passed through and I was without internet all night :).   Looks good so far though.

I just wanted to mention there is already some C++ code existing that I wanted to drag into the compiler at some point during or after a rewrite; The user interface (command line options, various auxilliary functions) from the 'util' directory to replace much of osutil.c.   I have a preprocessor in C++ (the ocpp directory) and I have the object file format stuff (objlib directory).   There is also the existing assembler core that I wanted to replace the compiler's with at some point...   I think that is all I have right now though.   I want eventually to get to the point of sharing as much code with the rest of the code base as possible :)

**Comment by chuggafan** [comment]
Ok, so an update for what I've done so far:

I've made an ErrorList now, and began to fill it out.

I have a keyword list and running the current program gives a dump of all keywords (you can modify the list dumped atm by going into occRewrite.cpp and changing what option is listed there).

I have the basis for the Language options with settings, but I have no command line parsing for options setup yet.

I am currently stuck on trying to figure out how to implement getsym because it's so complex, specifically the lexer pool stuff and the lexer context stuff is confusing enough for me to be a blocking issue of which I'd like to have some help with. I should have set up the basics enough to figure it out from where I have it.

On the topic of the current c++ preprocessor: I'd like to actually completely integrate it with the compiler, as the one you made when looking at it previously missed a few key features as well as had less features than the one built into the previous compiler, having it inbuilt into the compiler also (should) allow for deeper ability later on to use the compiler as one unit when creating a language server (as you previously did with occpr).

Hopefully the way I'm doing this with this still makes sense, though.

**Comment by LADSoft** [comment]
yeah that makes sense.   What are the problems you see with the C++ version of the preprocessor?   I *thiought* I had been able to keep it up to date.

Do you have specific questions about the lexer?   Do you want me to write something about it?   FYI the main complexity with it is that sometimes while parsing, the compiler will keep a lookaside table of all the parsed symbols so they can be fed back into the lexer later for example to instantiate the body of a template function.   Or an inline function, or certain types of data.   Otherwise the lexer is mostly run-of-the-mill.

I'm getting ready to pick up where I left off on the variadics problem...

**Comment by LADSoft** [comment]
on the preprocessor - there was no intent to keep it as a standalone preprocessor.   I don't know if you noticed what I did with the original preprocessor, shared some files between the compiler and a standalone preprocessor?   Similarly the linker shares some files out of the librarian directory but doesn't use the librarian standalone insofar as linking goes.   Oops I forgot to do #pragma once lol!   The intent was to do similar, use the library formed for ocpplib and then write separate glue in the compiler to get to the necessary data.

the lexer contexts...   the only good reason for having a pool of them is that the memory allocator is kind of rudimentary, allocate randomly but only free in large chunks at set times?   I've been toying with the idea of getting rid of memory.c and just using straight memory allocations in the future.   A lot of the code would become cleaner, and you wouldn't need things like the lexercontext allocated pool any more.

There are a couple of things that copy lexer contexts...   for example the function 'getDeferredData'  reads a chunk of the program in and parses it then caches it for later.   It is intended to read either a function body or the snippet that does the inline initialize during variable definition.   You CAN move about forwards and backwards in this things, or really to any random place you want.   You just have to have some notion where you want to move to.   For example when reading a function body with getDeferredData it usually gets cached in sym->deferredCompile; then functions like 'templateFunctioninstantiate' or 'deferredCompileOne' set the current compile state to compile out of that cache (for a specific function) instead of continuing from the current point in the file.   They do this by calling 'SetAlternateLex' and giving an argument of 'sym->deferredCompile' to set the lexer state to the new location.   Another call to 'SetAlternateLex' is made later with an argument of NULL, to return to the main stream of the compile.

Another thing that is sometimes done is a kind of backup; for example the function 'startOfType' needs to read sometimes quite a distance ahead in the stream to figure out whether the current expression is a type or not.    But the compile needs to continue at the same place it was before 'startOfType' was called.    To deal with that, startOfType caches the current context in a variable called 'placeholder', and when it is done scanning it calls a function 'prevsym' to set the context back to where it was at the beginning.   At this point, sometimes several symbols have already been parsed and the lexer (e.g. getsym) will process through them the same as if you had called 'SetAlternateLex' to change the context, until it runs out of parsed data.   Then it will go back and start parsing from the file again.

Another function that does this sort of thing is 'nestedPath'.   It sometimes needs a little lookahead to determine if there is going to be another '::' symbol.

Then I also added a function 'backupsym' because on rare occasions it is useful to look one symbol ahead to see what is coming, and it seemed more self-documenting to have a helper that would go back exactly one symbol than to force you to save the place in a placeholder variable.

I think that covers it all?   If you have any questions let me know and I will elaborate :)

**Comment by chuggafan** [comment]
Ok, so quick update:

I've been running through everything (You can see the progress on my repo) to move 100% of the C++ code currently made into namespaces so that it's organized by namespace and, well, actually can function. I've also taken the liberty of converting a large number of functions to accept size_t when they should to get rid of signed type mismatch warnings, because size_t is guaranteed by the standard to be the maximum size of an array.

I've also had some problems when going through with the namespacing because apparently visual studio likes to get its panties in a bunch over having a namespace in certain places with a certain way, which means it currently generates (on some projects) 1.5k errors, I plan on fixing this of course, but I wanted to get the commits through so I can't possibly lose progress and that it shows that I'm still working on something.

The preprocessor still needs to have ```#pragma once``` added into it, and I still need to work on actually rewriting, but that comes second to namespacing everything properly so that it doesn't bug out whenever I try to use something properly.

I also noticed when going through some of the old DOS code to format it that oftentimes there were calls to do... ```sub eax, eax``` or ```sub ecx, ecx```, specifically there are a ton of examples in dpmi.c, is it O.K. to assume that these can be replaced with a simple ```xor eax, eax``` or ```xor ecx, ecx```? [This stackoverflow post](https://stackoverflow.com/questions/33666617/what-is-the-best-way-to-set-a-register-to-zero-in-x86-assembly-xor-mov-or-and) explains why it should always be ```xor $reg, $reg``` instead of  ```sub $reg, $reg```, so I hope that explains my reasoning about asking, even if it's rarely used it's still a thing to look out for in say the optimizer section.

Hopefully this is a good update on what I'm doing. (oh, and I'm going around replacing some instances of CRT_NO_SECURE_WARNINGS and then moving to the nonstandard but microsoft likes it versions of functions, e.g. fopen_s is common for me to change everything to because it's actually better for checking if the args are bad or if it opened properly).

**Comment by GitMensch** [comment]
> Hopefully this is a good update on what I'm doing. (oh, and I'm going around replacing some instances of `CRT_NO_SECURE_WARNINGS` and then moving to the nonstandard but microsoft likes it versions of functions, e.g. `fopen_s` is common for me to change everything to because it's actually better for checking if the args are bad or if it opened properly).

Doing so would force you to provide wrapper functions for compilers that don't provide these functions - https://stackoverflow.com/questions/1513209/is-there-a-way-to-use-fopen-s-with-gcc-or-at-least-create-a-define-about-it - looks good.
I'd actually prefer to keep the (pre-C11) standard functions.

**Comment by chuggafan** [comment]
Fair enough, GitMensch, I know that some of them are actually easy to replace for c++ (strcpy_s has a templated form that works wonders for something so basic. Clang also complains about it (not just MSVC) and decides that instead of using anything that even exists within a standard (!!!!!) that you should use strlcpy, which *LITERALLY* only exists on *BSD and Solaris. Neither operating system is supported by OrangeC. 

Onto what I have questions about now:

I have started to run through the files with clang-tidy (because it works for a lot of static analysis issues and wow does it seem to do a pretty good job for the most part) and it seems to have found these areas of problems (I'm not applying them directly because I want to understand the rationale for areas), I'm going to only post the stuff found in ```occ``` itself so that there isn't literally THOUSANDS and THOUSANDS of complaints from it to go through.

An example of this is line 164 of lambda.c
```while (check && !error)``` is located here, it is complaining that error always is true because it evaluates to a function (which exists).

The way that the YML file I'm dropping here is structured makes little sense until you realize it's made for another clang tool, namely clang-apply-replacements, which ignores lines and just goes for positions in file (raw positions).  Here's the file in text form (github rejects the YML form): 
[fixes.txt](https://github.com/LADSoft/OrangeC/files/2321136/fixes.txt)


I've taken the liberty of removing all references to strcpy being unsafe to use from the file as well as one part where it attempts to get "WinMode" changed, and removed WINMODE.H (the one located in occ/x86 which is the same thing as the one located in occ/parse just different capitalization for the file name) entirely. If you want to replicate what I got I ran the REGEX ```\- \{DiagnosticName: clang\-analyzer\-security\.insecureAPI\.strcpy,.*(\n.*?)*}``` on the output I got from clang-tidy then ran the regex ```\s+\n``` with a replacement of ```\n``` (because VSCode can't handle multiline regex).

The way I ran clang-tidy to get these results is weird, the first thing I had to do was get the SourceTrail Visual Studio extension and dump occ into a compile_commands.json compilation database (because SourceTrail can do that really well). I then take this and feed it into run-clang-tidy.py so that it only lists the fixes once for each thing. The command I used was: ```python "C:\Program Files\LLVM\share\clang\run-clang-tidy.py" -p=. -header-filter=.* -checks='clang-analyzer-*,cert-*,portability-*,-misc-*,bugprone-*,performance-*' -export-fixes fixes.yml```
to dump the fixes that it wants and the warnings it gives. When you do that clang-tidy will output a nice (colorized and multithreaded which kills your command prompt colors sometimes) output of all the warnings AND their rationale for it being warnings, such as it will show you what branch it would take to be able to come to the conclusion it does. Although I would take a lot of the conclusions with a grain of salt though, specifically for null pointer dereferencing (since it can't make the assumptions made elsewhere from the caller). Other conclusions it makes seem to be fine (e.g. it can correctly find when parameters are unused and that they should be dropped, as well as missed parens around macros). I'm going to do similar checks with ALL of the projects within the solution (and have been doing so now) but certain changes are good to look through.

If you want a file with all of the null dereference cruft removed so it's easier to go through (I also removed duplicate floating.h warnings): 
[fixes.txt](https://github.com/LADSoft/OrangeC/files/2321162/fixes.txt)

Sorry for what pretty much amounts to a text dump, I just wanted to point at some of this and ask, "What's up with that?". If necessary I can make a quick tool to convert the fileOffsets to actual line/column numbers instead.

**Comment by LADSoft** [comment]
I looked briefly through fixes.txt...   looks like there is a lot of defined but unused stuff going on.   The other thing I saw immediately was the casts between list types...   yeah that is one of the shortcomings of the compiler sources, type safety is sometimes ignored.   the LIST type is a generic list but various other list types have been defined; the first element of each structure is usually a NEXT pointer so it least during traversal they are identical.   It is just that you have to cast to get the appropriate fields...   I really ought to fix that I guess.    The other projects are much more reasonable about the sources being type-safe though.

I will look more closely tomorrow...

**Comment by LADSoft** [comment]
here is some comments on the fixes.txt:  
[commentsonfixes.txt](https://github.com/LADSoft/OrangeC/files/2334444/commentsonfixes.txt)

**Comment by chuggafan** [comment]
Update: I've been doing a lot, I've been attempting to re-write the preprocessor to support __has_include and \#pragma once, however this is a difficult task

I've also started to muck around with the c++ exceptions stuff, so that it supports c++17 exception stuff as well as rely more on inline building libc++ altogether rather than compile it separately, my plan is to implement the exceptions entirely and start to remove the shims that are inbuilt into the compiler, I'm currently working on this the most, because it's interesting.

I've been also working on actually doing the re-write of the compiler, I've gotten past some issues in the tokenizing constructor, but I ran into some issues with the tokenizer not saving the previous tokens and need to be able to store them. This is because c++ requires backlookup for stuff, unlike what the tokenizer is built for. I also need to figure out how to inline run the pre-processor and make it give better diagnostics (line, column), because that way there's more info on where errors are, which the current pre-processor setup blocks entirely.

I feel like I'm going to need a lot of help overall at this point to get over the first hurdle, but so far I've been slowly working on it as I have the time.

**Comment by LADSoft** [comment]
I'll be working on reworking the compiler to use .CPP file extensions this weekend...

**Comment by chuggafan** [comment]
Sounds good to me, I kinda dropped what I was working on overall once it was all going to change anyways. I do feel like we have a lot of opportunities to make certain parts of the compiler into classes, and once this goes to just being C++, I'll wrap everything into a namespace ASAP so that we are at least keeping things separate, it should also help us find out weird dependencies and definitions...

**Comment by LADSoft** [comment]
yeah I figured having the compiler code in plain C is one of the blockers and wanted  to address it now rather than later :)

**Comment by LADSoft** [comment]
881e35e45439b80de62831b1cfb0a503be3e65e6
369897c814b0a5cd6721dcd72a13687e406704ab
8f69d0029a4e62dbfa79ddae21cd55be22744299
c2c2c5b68e9e9bace655ad6bd12ecd76c80f4a54
4703537c8b587bf7e4b3c4d98340c610b2f66b31
b21fe4b64f6882505080d684c5ca6e66118448c2
b69e31539721d5ea562cdc3dd9b0be9468d6529c

**Comment by GitMensch** [comment]
@LADSoft I'm confused - do you see this as "finished" or as "open"?

**Comment by chuggafan** [comment]
I think more specifically he sees this as an accident for having reopened this ;)

**Comment by LADSoft** [comment]
hehehe....    sorry for the confusion.   This issue is complete.

For some reason this issue hung around in my 'open issues' list even though it was clearly closed.    So I reopened it then immediately closed it in an attempt to get it out of the list...
