### ISSUE TITLE
oasm: extend support for gas directives

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#236]
This is a "group" ticket without any urge (I may drop some specific requests here, too).
For a full lost of directives supported by GNU assembler see [binutils manual for as, directives](https://sourceware.org/binutils/docs/as/Pseudo-Ops.html#Pseudo-Ops).

**Comment by GitMensch** [comment]
The next one for MPIR's configure would be `.align`:

```asm
      	.data
      	.align  4
	.globl	foo
	data1	1
	.align	4
foo
	data1	2
```

which features the error

> Label '.align' already exists.

**Comment by GitMensch** [comment]
Retested with current release, MPIR's configure still stops here so ping @LADSoft :-)

**Comment by GitMensch** [comment]
Shocking: MPIR configure scripts pass (it doesn't build but that's a different issue).

To the implementation of `.align`: I'm not sure if this is good/bad but likely it would be better if the two would say "yes":

The first test is the same as above (now compiling) with the title "checking if .align assembly directive is logarithmic" (which currently results in "no").

The second test "checking if the .align directive accepts an 0x90 fill in .text" with the code

```asm
	.text
	.align  4, 0x90
	.byte   0
	.align  4, 0x90
```

and occ resulting in

> Error conftest.s(2): Expected ']'
> Error conftest.s(4): Expected ']'

Do you see an option to tweak this?

**Comment by LADSoft** [comment]
@GitMensch -

I'm working on this now.

there are some things I don't want to implement, for example all the debug info support.   And things that are specific to object and executable file formats I want to elide as well.   I'm also not wanting to go to a lot of effort to beef up the listing file support at this time.

The major useful thing I don't want to implement if I can help it is .macro and friends, because the macro syntax in oasm is wildly different from the one in GAS.    But I'll implement it if you think it a requirement...

There are also a lot of directives which don't seem to apply...

Directives I'm not implementing that might actually matter will generate a warning if they are used.   Other directives such as the debug info directives will be accepted but silently ignored.

I'm thinking, make a first pass that implements the most needed stuff - fills, aligns, section handling, stuff like that...  and then if you have specific things you run into which we need I can look into it later.

Does that sound ok?

**Comment by GitMensch** [comment]
Sounds like a good plan. Concerning the warnings I'd suggest to ensure these get a warning option (enabled by default) which can be silenced or made a error.

The macro support will be important to be able to compile existing code, but it is perfectly reasonable to split this part from this issue and drop an "unlikely to happen anytime soon" note there.

**Comment by GitMensch** [comment]
We now have `oasm --gas` - how do we specify the oasm flag when invoking occ?

**Comment by LADSoft** [comment]
@gGitMensch

well that was easy, you had me add the -p (passthrough) switch to OCC a while back...   I just tried and this seems to work:

>      occ -pa--gas test.s

where -pa says 'pass flag to assembler' and the .s file extension signals the assembler should be called for this file.   It also understands the file extensions '.asm' and '.nas' for assembly language files.

**Comment by GitMensch** [comment]
@LADSoft  I've remembered that there was something like this but `occ --help` misses that information. Should I create a new issue for this?

**Comment by LADSoft** [comment]
yeah if you dont mind.

**Comment by GitMensch** [comment]
:-) I've did so on 28 Oct 2018 #260
