### ISSUE TITLE
Add __has_include and pragma once to OCPP

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#244]
Currently in my rewrite of a lot of the systems in OrangeC I noticed these two not existing in it, __has_include is a c++17 feature (so we'll need to add it anyways at some point), and pragma once is a nicety that OCC has but not OCPP. I did add \_\_COUNTER\_\_ to my current rewrite branch, though

**Comment by chuggafan** [comment]
Related to this in terms of rewriting:

C17/18 has recently been released, we should work on the library to fix any DRs found in the program and then just map any C17 standard to the C11 implementation, [here](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm) is the list of everything that has been changed by C17/18

**Comment by LADSoft** [comment]
ok i'm good with that, need to get back to where i was on fixing issues you had while compiling the library changes you were making.    As I recall, I had fixed an issue so that it compiled but it didn't compile properly...   I'm going to try to get serious about this again later this week.   I'm outta town for a few days in the interim though...

**Comment by chuggafan** [comment]
I know you're working on #227 atm, but do you have any idea what happened to this? the OCPP pre-processor is one of those things that I know that I have no idea how it works correctly, so I don't think that I could do this on my own at all.

**Comment by LADSoft** [comment]
ok so this should work now :)

**Comment by chuggafan** [comment]
Wow! faster than I expected.
