### ISSUE TITLE
Adding builtins support to OCC

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#264]
Currently builtin operators in OCC have to be added via an assembly that's compiled then referenced outside, a better methodology would to have a list of BUILTINS associated with types, parse THAT out, then work with that from there.

I'm currently attempting to implement this on my own time, as it's something that's not only useful but actively encourages optimizations, as the current method has to call an outside method rather than insert its own.  For example, the __builtin_clzll function we have implemented is not only not optimized, it re-implemented functionality that exists on the i386:

```asm
___builtin_clz:
___builtin_clzl:
    mov ecx,[esp+4]
    sub eax,eax
join:
    jecxz full
lp:
    shl ecx,1
    jc  done
    inc eax
    jmp lp
full:
    add eax,32
done:
    ret

___builtin_clzll:
    sub     eax,eax
    test    dword [esp+8],0ffffffffh
    mov     ecx,[esp+8]
    jnz     join
    mov     eax,32
    mov     ecx,[esp+4]
    jmp     join
```

All the compilers can generate the code on their own with their instrinsics: https://godbolt.org/z/tDp7fe this is a useful tool to bludgeon the compiler into doing more optimization by giving it more information to work with.

Now, I have a question related to this, there are mentions EVERYWHERE in the compiler about intrinsics, do they refer to these kinds of "intrinsics"? If so, would you be able to demonstrate how to add an instrinsic to these to allow me to add it the way the compiler itself intends?

**Comment by LADSoft** [comment]
yeah CC386 had intrinsic functions in the real sense, it could generate code for functions inline.   I *think* i completely implemented this same thing in OCC but stopped at the point of actually making any functions intrinsic.   I will look at it tomorrow nite...

**Comment by LADSoft** [comment]
the deal with the intrinsics is that there is the possibility of filling in a function pointer in the backend data structures (config.c) which gets called any time the intermediate code generator is trying to compile a function call.   If that function exists and returns a valid IMODE structure the intermediate code generator assumes that the backend code created a code sequence that was similar to calling the function.   For example calling gen_icode for a sequence of instructions and gen_label for labels,  gen_igotoor calling something more advanced like gen_moveblock to generate an entire sequence of instructions (in this case to move a block of data around, similar to memcpy).    One could also go up a level and create an EXPRESSION tree, then call gen_expr() to render it and get the result.   Bottom line is all the instructions generated will be treated as any other instruction, e.g. they will be optimized and registers will be assigned in the normal fashion.

**Comment by chuggafan** [comment]
So where do I fill these function pointers in and in what format?  I'm having a hard time figuring out where this is being inserted from, what sections of ARCH_ASM are being filled with this builtin function data? I have scarcely any idea.

I'm going to assume it goes like this:

First we create a char* of builtins, similarly to how cppbltin.c does it, then we insert it into the ARCH_ASM structure in the char* bltins data. (e.g. insert into said char* "int __builtin_ctzll(unsigned long long);" and have THAT be parsed).

We also create a function in ARCH_GEN, which is handleInstrins, which returns the IMODE of the intrinsic.

There's two things that are left that I would like to explain, the IntrinsicInit function and the SearchIntrins function in ARCH_ASM, what are they there for and what are they supposed to do? I (kind of) understand everything else (just have to screw around a bit in the code, well, a lot a bit), just would like to know the purposes of those two then.

**Comment by chuggafan** [comment]
So, I've screwed around a bit today with it and have discovered that:

Yes, you add the builtins as a string to the ARCH_ASM, then the ARCH_GEN function pointer handleIntrins is also added.

You take the input expression (node) and immediately make a functioncall pointer to hold the functioncall (it's better to reference that than keep writing node->v.func), and start using it.

To determine the name, use !strcmp(func->sp->name, $builtinname) to see if it matches up.

Now, I have NO IDEA where to move on from here, I don't know how to take the program I have:

```c
int main()
{
    return __builtin_ctz(12);
}
```
And transform this into the following:

```asm

global _main:
    mov eax, 12
    bsf eax, eax
    ret
```

Or even better:

```c
global _main:
   mov eax, 2
   ret
```

Where to start on that? There's like 30 different generation functions and 15 ways to create AModes that I'm sort of confused at that point.

**Comment by LADSoft** [comment]
really intrinsicSearch returns intermediate code not the final assembly code.    The intent i suppose was to compile the prototypes in intrinsInit (similar to how cppbltin.c works) then hand-generate the intermediate code.   But that doesn't play well with instructions that need to be done in assembly language (like bsf).   While you can do it the fact of doing it will cause the function you are compiling not to be optimized...

**Comment by chuggafan** [comment]
Yhea, I realized intrinsicSearch doesn't do anything (I can't even find it referenced anywhere, so I threw that away immediately). IntrinsicInit doesn't seem to do much either, at least at the moment.

I currently have just a thing for "int __builtin_ctz(unsigned int);" in ARCH_ASM for builtins.

My current "skeleton" for the HandleIntrinsic function is:

```c
IMODE* out_handleIntrinsic(EXPRESSION* node, int novalue)
{
    IMODE* value = NULL;
    FUNCTIONCALL* func = node->v.func;
    if (!strcmp(func->sp->name, "__builtin_ctz"))
    {
    }
    return value;
}
```

I want to go from here, to getting what we need. So I figured out that to actually grab the argument here you need to do (func->arguments->exp->left) and... that's where I am confused, how do I make this argument that I've passed in (the number 12, in this case), and make it, well, actually generate what I need, I believe the expressions here would be something like:

move 12 into EAX register.

bit scan forward output EAX, input EAX

return EAX

What kind of transformations do I need to make to be able to get something like *THAT* done, as far as I can tell it's... not the world's best documented thing.

**Comment by LADSoft** [comment]
yeah the problem you are having is that the way I have set the intrinsics up you can't easily generate backend instructions, it needs intermediate code.   I started thinking about that though and decided there is no reason we couldn't rework the intrinsics to be generated in the back end rather than in the intermediate code.    Then we could generate assembly language directly which arguably is more important for these kinds of uses anyway...   the one stumbling block that I see is that if we delay it to the backend then the arguments have been pushed on the stack.   This may not be entirely a deal breaker though as there are at least a couple of free registers at that point, and we won't be doing really complex stuff.  (I'm arguing that the PUSH instructions can be replaced with a move to register; something has to delete the CALL and any following stack adjustment any way so the code is going to be modified at this point).

I think I can tweak it pretty quickly so after dinner I will look at rearranging the sources then demoing a simple intrinsic function for you :)

But to answer your question more directly so you'll have some idea how to proceed once I get through with that, to generate an instruction at the backend you would use one of the gen_code variants.   Those all take an opcode, possibly a size value, and then AMODE style operands.   The opcodes should all be x86 instructions prefixed with op_, the size when specified is one of the ISZ_ constants found in middle\iopt.h, and the amode is generally generated from a function call.   Common function calls are:

makedreg(EAX) // creates an AMODE with a register for EAX
makefreg(n) // creates an AMODE for floating point register n
aimmed(number) // creates an AMODE for an integer immediate
make_floatconst(AMODE) // takes an amode which describes the EXPRESSION node for a floating constant, and modifies it to be FLD0, FLD1, or load it from the data segment
make_offset(EXPRESSION *s) // takes an expression describing a variable and makes an AMODE for it
make_stack(n) // get a pointer to a location relative to the stack pointer

those are the main ones I guess.   So load load twelve into ECX:

gen_code(op_mov, makedreg(ECX), aimmed(12));

and to add 12 to dl:

gen_codes(op_add, ISZ_UCHAR, makedreg(EDX), aimmed(12));

Another way to do the latter is:

AMODE *dl = makedreg(EDX);
dl->length = ISZ_UCHAR;

gen_code(op_add, dl, aimmed(12));

where the sizing is set implicitly based on the operands.

as you can see it proceeds pretty much like in assembly language except for the explicit creation of the operands, and the explicit sizing.   

it gets just a little harder when you want to do an indirection through a register, the easiest way to describe [EAX + 44] is:

AMODE *x = makedreg(EAX)
x->mode = am_indisp;
x->offset = intNode(44); // use intnode from the front end because we need a frontend expression here

you could set the size of the resulting data (not the register used for indirection) by doing this:
x->length = ISZ_USHORT;

to describe 'word ptr [eax + 44]'

there is also am_indispscale to add scaling.

I don't have a function for these because usually such things have been generated by getAmodes from the intermediate code.

**Comment by LADSoft** [comment]
ok so in conjunction with this I realized we really need __fastcall support to streamline it (#265).   Fastcall itself was easy to implement, but then I got lost in a maze of trying to get the this pointer (in C++) to work as a fastcall parameter...   the upshot  after a lot of time spent being we are only supporting fastcall in the C language so we can streamline this issue and I can seriously devote time to #227.   Later we can fix the this ptr to work better.

The basic idea being that with the __fastcall if you keep the parameters to a minimum parameters will be put in registers rather than on the stack, and so there will be no maintenance needed to be made to the generated code.   A short hook in asm_gosub will detect the builtin you want to generate code for (again by string comparison with the file name) and if so you can just add the code as described in my preceding paragraph instead of generating the call instruction...

I'll write a demo tomorrow nite...

**Comment by LADSoft** [comment]
I added assembly language intrinsics with a couple of test functions 'rotateLeft' and 'rotateRight'.   The code is in a new file beIntrins.c.    Here is a simple program that exercises it:

    main(int argc, int argv)
    {
    	    printf("%d", rotateLeft(argc,4) + rotateRight(argc, 16));
    }

**Comment by chuggafan** [comment]
Sounds awesome! I'll get to work on this one soon, then. Once I add my builtins (and probably modify the builtin function a little) I'll close this issue, sound good?

**Comment by LADSoft** [comment]
sounds good.   You can remove the two builtins I added; I only added them as a demonstration.

**Comment by chuggafan** [comment]
Closing this. We can add more builtins at a later point, the current ones I've added should be simple enough, (e.g. BSR, BSF, CTZ, ROR, ROL, OUT, IN), however we can always add more, especially to be compatible with other compilers, as I said on my PR, I'll make a separate issue relating to the optimization of these builtins soon.
