### ISSUE TITLE
Allowing for injection of custom IsSymbolChar in OCPP

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#291]
So this is less of a required thing that I need for OCPP than something I noticed trying to do a bunch of minor improvements to everything at once:

OCPP has IsSymbolChar and IsSymbolStartChar, recently, on my minor improvements, I have found out that DefFile.cpp in oimplib makes these as well, presumably to override the OCPP variants, due to some minor change I made this causes a linker error, due to multiple definitions, meaning the build system broke due to something I changed, I have no idea how, and that the previous method to override the IsSymbolChar and IsSymbolStartChar functions are flakey, any ideas? If you want to see what I did that might have caused them to start to conflict, I'll push my changes so far to github, otherwise ¯\\\_(ツ)\_/¯.

**Comment by LADSoft** [comment]
yeah this is kind of a kludge in want of a better design.

if you didn't know the builds are done with libraries, so all the files in the ocpp directory other than the main line file are stuffed into a library and then other projects are linked against it.

It looks like the file 'preprocessor.cpp' in ocpp directory would normally never be linked into any other application, because by design the only thing that referenced it (other than for the IsSym* pair) is ppMain.cpp and this is the main line used in the ocpp project.   

OTOH if you put something in the project that causes preprocessor.cpp to be linked in all the time,  then you would get the IsSymbolChar and IsSymbolStart char from that file in addition to any defined in the other project.   Thus a collision?   This could be a new function in preprocessor.cpp which you reference elsewhere, or it could be a reference elsewhere to the PreProcessor class.   Or if you were to delete one of the two functions that would cause the collision as well...

**Comment by LADSoft** [comment]
I reorganized some code and it should alleviate the problem...

**Comment by LADSoft** [comment]
I'm fixing this by adding a function pointer member in the Tokenizer() class...
