### ISSUE TITLE
braced initialization of array type runs compiler out of memory

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#333]
std::array<int,10> aa = {1,2,3,4,5,6,7,8,9,10} 

fails

**Comment by chuggafan** [comment]
Found the problem function: allocate_desc seems to allocate a LOT of stuff and never lets it go, and in this case seems to hit an OOM error before it hits a Stack Overflow, so I think that might be the problem....

**Comment by LADSoft** [comment]
thanks.    One of the things that needs to be done now that we are compiling as C++ files is to rework the memory management...   when I wrote this it was like, lets just make memory pools for various temporary work, and rather than do individual deallocations lets just deallocate the entire memory pool when not needed.

Originally there was just a global pool (for global assignments and #defines and so forth) and a local pool (used during compilation of a function).    The local pool would be deallocated when compilation of a function went out of scope...  the global pool initially got deallocated at end of the compiler's run but eventually that got changed when the compiler started supporting compiling multiple files in one run.

But unfortunately when I started adding inline function declarations I had to make the local pool essentially an extension of the global pool, and to make up for it I put in various other pools in the optimizers lol!   But I'm sure there is a *lot* of temporary stuff getting stuck into the global/local pools sigh.    Anyway I think the whole thing needs to be redone in a more modern way but of course that is a really huge project, and probably ought to be done in conjunction with other things that modernize the code base such as scoping things into classes...

I haven't forgotten you asked to have the thing split into three parts:   the parser, the optimizer, and the code generator lol!    Which would also allow us to things like this piecemeal and with less impact on the entire project.   I've been debating whether to do that as the next large project or whether it would be better to do C++17 first....

**Comment by chuggafan** [comment]
Yhea, when I was thinking about this earlier I did think about the fact that it seems that #297 clears up a LOT more than I first anticipated because it forces us to re-think the entire build process, meaning that each module (I'm looking at you, optimizer) is broken up into it's own section and is independent of any other module in the process.

I do think that in this case though, the OOM error is caused by the while loop running the lines that I mentioned, it's not terminating for some reason and I will investigate the cause on this later today....

Although, on the memory management per section, the fact that each section has it's own "how much memory has been allocated" pool is a nice idea showing where we need to work on in terms of section for any given program, it's nice and would be similar to a timer on each part of the process on time spent (e.g. time spent in the optimizer, what functions are the problem functions in the program, rating individual blocks in time spent compiling for being able to isolate issues, etc.).

I definitely agree though, the whole program needs to be modernized, and I still think that being able to work on it piecemeal is better than a scrap-re-write I tried at one point.

**Comment by LADSoft** [comment]
I've historically done quite a bit of profiling.   Back in the day I had written my own profiler, which worked by having the compiler instrument the code with calls to the profiler....   I think the code for the profiler is still part of the library build...   right now I'm using an external profiler called codexl any time i need to find timing bottlenecks...   sometimes i stop and run it for a couple of days to see what i can clean up.   Wish I had more time to devote to it though...

**Comment by LADSoft** [comment]
I wondered if you got anywhere with this?

**Comment by chuggafan** [comment]
I have a surprising amount of things I have to do recently, so other than knowing what loop is causing the problem I currently have no idea.

**Comment by LADSoft** [comment]
hm doesn't have any kind of non-default constructor...   but the actual problem was it was trying to initialize types and functions lol...
