### ISSUE TITLE
fix build

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#358]
build is randomly breaking.   I fixed a problem in omake but there is apparently also a problem in the compiler.   Hope to have it fixed soon.

**Comment by LADSoft** [comment]
the build seems to be working for the moment.   Unfortunately the only change I made was in response to the fact that the latest version of mingw32-make has obvious issues when I run it on my current computer...   I basically removed references to it from the builds.   Even though I don't know specifically that there are other issues that would cause the builds to fail.   I'm going to do a couple more control builds and if that goes well I'll revert the change to see what happens.

**Comment by chuggafan** [comment]
Seems like the builds should all be failing, https://ci.appveyor.com/project/LADSoft/orangec/build/job/ci5lrnu32ok0pkyt?fullLog=true I ctrl+f'd this for "diagnostic" and the compiler is throwing around plenty of them, though since the build is parallel it's not telling us where. This seems to be a problem with multiple parts of the compiler on just the standard library. And since this is a "buildable" section... that does not bode well for the "unbuildable" sections...

**Comment by LADSoft** [comment]
it is usual to get a bunch of diagnostics.   Guess I need to clean that up to avoid confusion sigh.

Otherwise, still testing.   There seems to be something up with mingw32-make.   I have problems with it at home too.   Will get back to you whenever I make a final conclusion on that.

**Comment by LADSoft** [comment]
ok so I don't know if there is a bug in occ but I do know that any time I try to use mingw32-make it doesn't work and any time I use omake it does.    mingw32-make also has a problem on my computer with just hanging in the middle of a build (I have to type 'exit' to get it to close an extraneous DOS prompt that should never have been opened).   These problems seem to have surfaced since I upgraded the mingw64 version to support C++2014...   I'm going to assume mingw32-make is broken until I have a reason to believe otherwise.

**Comment by GitMensch** [comment]
So #397 may help to fix this?

**Comment by LADSoft** [comment]
Apparently my fix for #377 caused the most recent problems.    But now there is another problem with builds going beyond appveyor time limits.. (which may or may not be related to similar problems with recent test builds)  am evaluating whether this is a real issue or just an issue because during the day appveyor loads are higher.

**Comment by LADSoft** [comment]
after resolving the issue I rewrote the build so it would take less time.   By splitting OCCIL out into its own build.   Well mostly, I do build it once at the end so I can throw it into the distributions :smile:

**Comment by GitMensch** [comment]
Good workaround. One question though: does OCCIL takes very long to compile and if yes why?

**Comment by chuggafan** [comment]
AFAIK It's that there's so many tests, and running it with 4 threads means it takes awhile. We should probably work on the compiler speed however because it still is really slow, but that requires huge re-writes...

**Comment by bencz** [comment]
Probably, the problem is in the DotNetPeLib.... It's took a long time to
read the entire dll/exe, to take usefull informations to the compiler

**Comment by chuggafan** [comment]
You might be right, I've noticed a lot of potential slowdowns inside of it, one such is that during output it uses a LOT of std::endl, this is bad because std::endl flushes the buffer, it's better to just use newlines for whatever platform if you DO NOT need a buffer flush.

We should still get files that we know take a long time and put pressure on the compiler then start profiling that section and any of the new sections so that we can eliminate as much slowdown as possible, if you can get me any files that have that attribute I can definitely find the time to profile them.

**Comment by LADSoft** [comment]
I need to look at occil separately.   Coverity is still unavailable so maybe I can do that tonite.   Maybe they took a break for the holiday?

A recent patch sped up occ a bit for C++ code, but occil still runs slowly for some reason.  As Alexandre pointed out is definitely in the PE file parsing; I know exactly which routine it is in most often and what I saw there when I looked is why I was inspired to do other fixes to speed up occ.   It really helped when compiling occil with MSVC, but it didn't help for whatever reason when occil is compiled with occ.

Overall things seemed quite a bit faster in code that would trigger exception handling overhead.   (unfortunately I didn't get good benchmarks off appveyor because I had already added occil...)   But another thing I did was speed up the PE file parsing routines and they run much faster when compiled with MSVC.

chuggafan:  if you want to do some profiling there are some files that take quite a bit of time in the distribution.   For example sqlite3.c takes 9 seconds currently.  I think msvc compile for it is down around 6 seconds if I remember correctly...   in the oasm directory x64parser.cpp and x64stub.cpp also take unreasonable amounts of time.

In occ/parse I suspect expr.cpp, stmt.cpp and maybe declare.cpp could compile faster based on comparisons with the other compilers...

There may be other files as well, those are the ones that come to mind.

**Comment by chuggafan** [comment]
So I ran an instrumented compile of sqlite3.c (I had some modified lines in occ but they weren't even close to being the hotpath so it doesn't matter). 9% of all the time the compiler is using is just allocating memory via memAlloc, 3.2% is just memsetting memory inside of memAlloc, malloc itself is 2.31%, and more:

I use this file: 
[Report20190903-1408_CallerCalleeSummary.zip](https://github.com/LADSoft/OrangeC/files/3571426/Report20190903-1408_CallerCalleeSummary.zip)
I sort the file using Elapsed Exclusive Time % which gives me how much (excluding the calls to OTHER FUNCTIONS) time the functions take up, Elapsed Inclusive Time % includes calls to other functions (aka declare and main, etc. take up 99% of the processing time who could have guessed). This file should give us a good page on optimizing C compile times, but we need to find an individual file of C++ that we get really large compile times on so that we can fix C++ stuff.

**Comment by LADSoft** [comment]
thanks.   I think I have mixed feelings about the various methods of instrumentation.   I always get confused about what they are telling me...

FWIW the x64parser.cpp file in the oasm directory takes six to 8 seconds I think...   It has a lot of little C++ functions in it...

**Comment by chuggafan** [comment]
Yhea, but x64parser.cpp doesn't torture test things like template instantiations as much as it does C++ classes, we need more things to benchmark overall so that we can get a representative sample set of actual real-world programs. Something like Chrome would be great but getting gninja to recognize OCC and actually getting enough support so that chrome would even begin compiling would be.... taxing... to say the least. 

BTW for instrumentation in Visual Studio 2019 there's 3 kinds that we care about ever: Instrumented (this does function-level calls to track function times for each function and find hotspot calls for each function) CPU Usage (This takes random samples, it's basically tracking where the CPU seems to be doing the most work by cycle count), and Memory Usage (This tracks every malloc and free() and friend calls so that it sees where you're forgetting to free memory or see how much memory in general is being allocated and where, this would probably be good to use for removing as many allocation calls as possible).

GPU Usage is some DirectX stuff that only matters if you're doing graphics intensive stuff and since I don't think there's anyone doing GPU offloading for a compiler it has 0 application for us.

**Comment by bencz** [comment]
https://github.com/emweb/wt

This project take a lot of time to build with gcc/msvc++, this is a complex
project

**Comment by chuggafan** [comment]
I will have to look into getting it to compile, but I have a lot less time than I used to and I think that if it uses things like STL threads we're stuck at the "Properly support certain C++11 platform features that everyone expects" stage.

I still have yet to try to combine CMake with OCC so... that'll be an adventure, I might try it out with llvm first but getting anything working is basically RNG at this point because cmake can be really, really opaque at times.
