### ISSUE TITLE
Destruction of temporaries used in creation of local static variables

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#360]
local static variables which require complex initialization have a guard, to prevent them from being initialized more than once. Which is fine until something is initialized that requires a complex initialization of one or more temporary variables... then the temporaries are torn down, but outside the guard. So the temporaries are initialized once but torn down every pass through the function. This results in undefined behavior the next time the routine is called...

for example:

```
int brokenfunc()
{
     static map<string, int> localvar = { { "one", 1"}, { "two", 2} .... };
}
```
causes this behavior.

**Comment by LADSoft** [comment]
local static variables which require complex initialization have a guard, to prevent them from being initialized more than once.    Which is fine until something is initialized that requires a complex initialization of one or more temporary variables...   then the temporaries are torn down, but outside the guard.    So the temporaries are initialized once but torn down every pass through the function.   This results in undefined behavior the next time the routine is called...

for example:

```
int brokenfunc()
{
     static map<string, int> localvar = { { "one", 1"}, { "two", 2} .... };
}
```
causes this behavior.

**Comment by GitMensch** [comment]
That sounds as the most severe bug in the tracker. Do you know in which version this happened the first time (and the possible fixed version)?

**Comment by LADSoft** [comment]
it has probably been there since C++11 was added, I found it when debugging some code changes.    The complexity went way up on fixing it and I was trying to release so it is still an issue...

**Comment by LADSoft** [comment]
I think I figured out an easy way to fix this, will look  at it when I get done with #366

**Comment by LADSoft** [comment]
in #384, @Chuggafan remarked that when he tried a local declaration of an unordered map, the 'static' placed on it didn't work.

**Comment by chuggafan** [comment]
Note: the stuff I tried in #384 may or may not be about standards compliance, I'd have to seriously check because it was the same performance implications as far as I could tell for not "hoisting" the thing that is marked static and const outside of the function so that destruction and initialization happens outside of the function. The behavior of OrangeC was the same across the board with all other compilers and I'd want to verify what the intended behavior of a "static map" is in this situation.... I don't have too much time on my hand anymore but I'll at least do some digging sometime over the weekend in checking.

**Comment by LADSoft** [comment]
Static variables are supposed to be initialized only once.   If you change them the change doesn't get overwritten with a new initialization the next time the function is invoked.    

For the C language this design  is easily accomplished by making the static variable a kind of  invisible 'global' and plopping the value in at compile or link time the same way an initialized global is done.   But it gets more complicated when C++ constructors are involved because that initialization has to be performed at run time.

VC calls the constructor when the code path the map is on on is first executed and orange does similar.   A flag is used to determined if the initialization has already been completed.   Care is also taken that the destructor is run at an appropriate time.   for non-statics the slowdown you saw would be correct; nonstatics do have to be constructed and torn down each time the block is entered even if they are marked 'const' (because I suppose a constructor could have side effects????).

I'm not seeing what you saw, I dragged the definitions back into the function marking them 'const' and 'static'.   and started some compiles and there doesnt seem to be a performance hit?   I do remember seeing the hit when I worked on this function at some point and forgot to mark the map static....   which is where this issue came from, once I marked it static I had to address other compiler problems...

**Comment by chuggafan** [comment]
Hmmm, I might have been wrong then, I know I at least was testing for "const", maybe I assumed that "const" was alone in making it so that the map wouldn't have to be constructed and destructed every time? If that's the case I'm wrong and ignore me because I'm talking dumb stuff. I'll have to investigate further into seeing what made me say that but I have a lot of work to do and a lot more over the past week...

**Comment by LADSoft** [comment]
'const' makes it unwriteable by the program but does not otherwise change the storage from 'auto'.   That would mean a 'const' variable would be constructed on every entry into the function and destructed at the end.    What we needed was 'static' which initializes it once and destructs it when the program exits.

**Comment by LADSoft** [comment]
this seems fixed so I'm closing it.   There will be a further commit with regression tests.
