### ISSUE TITLE
Fix FPF usage to not overwrite the VTable pointers

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#377]
various parts of the compiler do memcpy/memset/memcmp on FPF structure instances.   These have a VTable so such references aren't kosher.   CLANG flags the issue verbosely.

**Comment by chuggafan** [comment]
Thinking about it, we don't do any FPF class derivations do we? So if we overwrite the VTABLES with anything but a memset to 0 we should be fine because the vtables still point to the same thing (even if the vtable is a different location it's still pointing to the same code). So I think that the prioritization in this case is to not overwrite the vtable so that the calls that it can make don't get ruined. In the future if we ever derive any classes from FPF this will become a much bigger priority to fix but for now I think it's just memset to 0's that are the problem.

**Comment by LADSoft** [comment]
yeah we don't override them.   I'll have to look; not even sure why the vtables are being generated offhand...

**Comment by chuggafan** [comment]
They might be generated because of C++ reasons, but generally it's only virtual functions, but I think we don't generate vtables for it either? Maybe? I'd have to do a thorough check. I think it's just clang being paranoid tbh but you never know.

**Comment by LADSoft** [comment]
fixed in PR #378

**Comment by LADSoft** [comment]
i jumped the gun this wasn't fixed yet...

**Comment by LADSoft** [comment]
it seems my fix for this caused problems with the build so I'm reopening.

**Comment by LADSoft** [comment]
I wasn't able to determine why removing 'virtual' from the destructor would make a difference.   As far as I can tell there is no reason for it should need a virtual destructor. Moving this to the next milestone...

**Comment by LADSoft** [comment]
on a related issue Coverity found some issues that aren't immediately a problem but that should be reworked anyway.   They are marked 'FIXME' in the floating.h/floating.cpp code files
