### ISSUE TITLE
replace preprocessor

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#399]
the preprocessor has long been written in C++ and is used for example in the assembler and resoruce compiler, it needs to replace the existing 'c' language implementation in the compiler.   Also remove the old implementation.

**Comment by GitMensch** [comment]
What is this issue about? I don't have a clue from the the title and text - I assume you have "an external preprocessor" and an "internal one" and want to remove one of those?

**Comment by chuggafan** [comment]
We should probably while we're at it add in __has_cpp_attribute and __has_c_attribute (C++ 20 and C2x respectively standard) so that we have the ability to feature test attributes (clang has had it for awhile and that's why it's being added to the standard). 

We should also change the preprocessor to, when evaluating conditional inclusion, evaluate all signed and unsigned integer types as intmax_t and uintmax_t respectively (this is in an #if directive). Sadly, the C standard has literally no clue about floating point numbers in this case so... but either way we should do this just so we're that much closer to standard (and future standard) compliance.

**Comment by LADSoft** [comment]
yeah there are two preprocessors...  one was originally written in C and is in the compiler now.   The other was rewritten in C++ several years ago and is used for example by the assembler and resource compiler.   I think it wasteful to have two modules that do exactly the same thing and want to get rid of the older one...
