### ISSUE TITLE
Bug: call of a wrong function in the code

### ISSUE THREAD

**Issue by dig386** [LADSoft/OrangeC#405]
I've found an incorrect compilation of the attached program (Orange C 6.0.42.1, Win32 platform). It seems that in some conditions the compiler calls IAPWS95OP_DH_coeffs instead of OP_DH_coeffs and goes into an infinite cycle. 

Note: the existence of the problem depends on the separation of the code into object modules and even from the order of command line arguments for occ (see makeit.bat in the attached archive).

[occ_glitch.zip](https://github.com/LADSoft/OrangeC/files/3581139/occ_glitch.zip)

**Comment by chuggafan** [comment]
You're right it does that, but if you assemble it then compile them together it doesn't do it, seems like some BIG clunk with the optimizer assuming things it REALLY shouldn't be.

**Comment by chuggafan** [comment]
So I went and compiled and decompiled the file after compiling it, so somehow the call to OP_DH_coeffs is being transformed to a call to IAPWS95OP_DH_coeffs, this is going to be some real weird stuff, but I can definitely confirm it's something going on in the linker.

**Comment by chuggafan** [comment]
So it's most likely somewhere in olink, probably relating to the LinkRemapper optimizing something incorrectly, but since I can't read .rel files and figuring out how it works properly... and I don't have the time... I'll defer it to someone else unless I can find the time to do it.

**Comment by LADSoft** [comment]
thanks chuggafan, you guessed the right function to look at if it was a linker issue :smile:.   I reviewed this and found it wasn't even trying to reference the function.  Looking at the object file for iapws95_dh_o.c it seems the compiler is trying to do the fixup itself instead of recognizing that the function is external...   which is course is invalid.   And I'm not sure why it is coming up here either.   FWIW it doesn't have anything to do with the similarity in the function names, I renamed the functions in the example dig386 gave to be totally oblique to each other and had the same problem.   

BTW there is a document in orangec\src\objlib\doc that describes the object file format in some detail.   It is an expansion on the IEEE-695 object file format (ASCII version).   The REL file format is pretty much the same thing except the inter-module fixups have been removed.

Looks like that directory needs cleaning though, it has a couple of different versions but they don't seem up to date with each other.   The HTML version is the latest.   But there are probably only minor differences...

I will fix this tomorrow nite.
