### ISSUE TITLE
installer: can only be used as local admin

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#414]
As we do have the zipped binaries this issue doesn't look like a high-priority item but may be done at some later point in time:

The installer refuses to work if not started as local admin, especially for a "memory stick" (or user-local) installation this is bad.

**Comment by LADSoft** [comment]
ugh, windows 10 won't let me add a user unless I have a legitimate microsoft-certified email address or want to use my phone.

the problems with this issue is, the admin priviledge is required by parts of the install.   That is why it is checked for...   but maybe I can degrade somehow if 'memory stick' is chosen.

Whenever I get a chance I'll dig up an older computer and see what I can see...

**Comment by GitMensch** [comment]
Ideally the admin privilidge is NOT done on executable level but by request from within the installer (normally on the final "OK" button, but only if a non-memory-stick install [which I'd suggest to name "portable install" as you don't need a stick for that] is chosen).
I haven't worked with creating Windows Installers for a long time, but that _should_ be possible _somehow_,

**Comment by GitMensch** [comment]
> ugh, windows 10 won't let me add a user unless I have a legitimate microsoft-certified email address or want to use my phone.

Yay, consumer OS with full cloud-based-surveillance / user-orientated web-storage (you know - everyone has internet everywhere and wants to sync their user-settings between lots of computers...)

I'd try with starting `lusmgr.msc`...
