### ISSUE TITLE
C testsuite

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#421]
I've just stumbled over https://github.com/c-testsuite/c-testsuite and thought to drop a note (primarily to @chuggafan for now to check the current results).

It may reasonable to add OrangeC CI to the automated testing on their site (seems to be possible "somehow") and/or integrate (parts of) this testsuite to the OrangeC tests.

**Comment by LADSoft** [comment]
I thought I would at least evaluate this sooner rather than later...   there are a bunch of syntax errors being generated by occ, some floating point printing problems, and a complex constant expression caused the optimizer to crash for one of the input files.   I'm fixing the latter now, and debating on whether to derail the current milestone to work on the other issues...

**Comment by LADSoft** [comment]
decided to bite the bullet as this doesn't look terribly intense, just some piddly stuff like not handling the statement immediately following a 'case' statement properly...   or not handling C99 casts into structure data definitions properly at the global level... (I honestly didn't know you could do that lol)   so these are good tests, thank you...
