### ISSUE TITLE
Is adding --output-def file reasonable?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#451]
Found in building MPFR - when building a shared library on windows it seems to assume that `--output-def file` is available. In its final linking it includes `--output-def .libs/libmpfr-6.dll.def `.

While this should be considered a minor bug in its build environment (I *may* find the time to deep-check and create a bug report there [or in gnulib, if this is used]) this bug/assumption may be more common.

Would it be reasonable to add this switch to olink "because it may be assumed to exist" and/or "for VS compatibility"?

Docs found in [LD Win32][1] with a reference in [gnulib VS compatibility][2].

[1]:https://sourceware.org/binutils/docs/ld/WIN32.html
[2]:https://www.gnu.org/software/gnulib/manual/html_node/Visual-Studio-Compatibility.html

**Comment by LADSoft** [comment]
we could add this.

**Comment by LADSoft** [comment]
I fixed this issue and some recently introduced bugs in oimplib, also added --export-all-symbols...

now there is a missing .o file,  and omake seems broken...   will get back to it tomorrow evening...

> libtool: link: rm -f .libs/libgmp.la-1.o
> libtool: link: occ --nologo -o .libs/libgmp-10.dll .libs/libgmp.la-2.o  --export-all-symbols --output-def .libs/libgmp-3.dll.def   `func_echo_all "" | /usr/bin/sed 's/ -lc$//'` -link -dll
> Error: Input file '.libs/libgmp.la-2.o' does not exist.
> Error: Library 'ink.l' does not exist or is not a library
> Error: Library 'l.l' does not exist or is not a library
>   
> 
>

**Comment by GitMensch** [comment]
> I fixed this issue and some recently introduced bugs in oimplib, also added --export-all-symbols...

Yay. Do you have some hashes for reference (or is the issue referenced in your commits and just not pushed)?

> now there is a missing .o file, and omake seems broken...

Rechecked: The error "Error: Input file '.libs/libgmp.la-2.o' does not exist." is also raised if neither ogrep nor omake is used.
This is the part where I'm stuck with building GMP via OrangeC :-(

Note: the `-link -dll` part may also be removed via config.status. (I assume you don't want to add them, too, do you?)

**Comment by LADSoft** [comment]
I havent pushed yet...   I need to make sure I haven't broken anything.   I will tonite.

I wasn't sure what to do with the part of the libtool:link:occ line starting with 'func_echo_all'.   I though it probably should have been weeded by omake and passed separately to the shell?   I didn't know if the -link -dll went with that.   So that was the primary thing I was going to look at tonite...   I assumed the .o file was supposed to be some type of mashup of all the input files?

**Comment by GitMensch** [comment]
This implementation looks wrong (from the help description) - here's the help for the related switches:

~~~
--out-implib <file>                Generate import library
--output-def <file>                Generate a .DEF file for the built DLL
~~~

Note: They *additionally* create the import-library/def file. OrangeC "implies" `--out-implib dllbasename.l` which is fine, using the switch would just override the default (it _may_ be reasonable to ask for a way to not create the import library, which seems be the default for the GNU toolchain).

**Comment by LADSoft** [comment]
I had some trouble with this because some of the documentation I saw has a comma between the switch and the value and that is the way I initially implemented it before I got disabused of that notion...   I think I have a mish-mash of an implementation at this point and of course the docs need updating.    I will clean it up tonite.   As far as --out-implib I'm not going to fix it right away but if you want to make a separate issue for it that is fine.
