### ISSUE TITLE
Get MPFR test programs working

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#460]
currently some of the MPFR test programs work but others exit with some kind of error.   And there is still an odd one here and there that just hangs...

This issue will be for going through the entire MPFR test suite and making sure OCC can generate good programs for it.

**Comment by GitMensch** [comment]
As noted in #440, there's also an access-violation in GMP's t-constants.exe.

**Comment by LADSoft** [comment]
FWIW the main reason for delaying this issue is so that I can make progress on the milestone for a while, I'll get back to it whenever I get #297 at least written and ready to be debugged...   but I'm close on that now anyway.

**Comment by LADSoft** [comment]
I fixed a crash and a couple of other issues, it gets through the tests but fails some of them.   It hangs on one for a long time, haven't checked if that is a crash or something else.   I'm going to finish up on #297 and then come back...

**Comment by LADSoft** [comment]
currently, 23/190 tests fail, 1 is skipped.   The others pass.

I'm on furlough this coming week, hope to get through the remaining issues and close milestone #2 before it is done :)

**Comment by GitMensch** [comment]
>  It hangs on one for a long time

I *guess* this test is about double/float and the missing internal optimization because the binary format is unknown (something that the GMP or MPIR configure script had warned about). But this guess could be totally wrong. If it isn't then the "correct" way would be to submit a patch or at least a note to GMP/MPIR/MPFR about the binary format used by OrangeC - or adjust the tools that dump the format, if this is the reason for these packages to not know about it.

Fixing the failing 23 tests is a real good way to ensure OrangeC works correct (some may be already fixed after inspecting the coverity reported issues)! I actually forgot about the test results with GMP, as it got a new release since the last test it would be good to redo the build and test with the current version of GMP + OrangeC - GMP and MPFR are both packages that "tend to show errors in external toolsets".

**Comment by LADSoft** [comment]
yeah I think that was the issue; there was an infinite loop in the core library when you tried to run the tests without any kind of floating point flags set for the compile.   I later set the floating point flags manually and it seems fine for the moment...    I will see if I can remember where the problem is...

I think the issue with the floating point detection is it relies on the object file being a binary file format, whereas as in orange c it is currently an ASCII format.   In milestone three issue #436 I am going to switch formats to binary anyway so we can see if this works any better...

**Comment by LADSoft** [comment]
down to 8 tests left.   Mostly they do I/O or check compatibility with DLLs...

**Comment by chuggafan** [comment]
So my question is why does the divide by 2 == shift down not work and had to be changed? it makes perfect sense to me.

**Comment by LADSoft** [comment]
I was having a lot of trouble trying to get the tests working again and eventually backed out of most changes to sdivide and udivide while in the process of trying to figure which of several changes broke it.   

I eventually remembered anyway that what I was trying to do in sdivide wasn't kosher, because shifting a negative number right by a power of two doesn't get the correct answer all the time...   only works properly for positive numbers.   

There are three approaches: do the divide directly (very slow); a comparison against zero then a branch around adding an adjustment (involves a branch), or letting sdivide generate a more complex sequence for it based on turning the division into multiples and shifts.   The first isn't an option, but I don't really have a feel for which of the last two would be quicker...   maybe I should go back to using a branch/adjust algorithm again.

I think udivide() still generates the optimized shift...   for unsigned numbers.

Anyway all I was really in there to do was fix (x%1) to work correctly- and I got sidetracked lol!  I ended up fixing that in constopt.c...

**Comment by chuggafan** [comment]
I'm not sure if you got my other comment but the changes you made to intmax_t and uintmax_t make OrangeC fall out of the C18 standard. (which is basically the C11 standard).
Section 7.20.1.5 states:
>The following type designates a signed integer type capable of representing any value of any signed
integer type:
intmax_t

And since the 32 bit intmax_t can't represent a 64 bit number, therefore our typedef is actually not standard conformant.

**Comment by LADSoft** [comment]
ok.   I guess there is a bug in mpfr then...  it uses uintmax_t in various tests and then uses UINT_MAX as the size instead of UINTMAX_MAX....   so the test fails sigh.   I will fix this back to its original format.

Then I'm going to close the issue without fixing the remaining tests...   I tied them down to FILE* being incompatiable between OCC and MSVC...   more can be found in the comments for #502.

**Comment by GitMensch** [comment]
> ok. I guess there is a bug in mpfr then... it uses uintmax_t in various tests and then uses UINT_MAX as the size instead of UINTMAX_MAX.... so the test fails

Can you please recheck with the MPFR folks? Despite the better understanding one of both projects will have a bug fixed afterwards....

This issue is not yet listed at [MPFR Bugs since last release](https://www.mpfr.org/mpfr-current/#bugs) and also not in the [MPFR bug tracker](https://gforge.inria.fr/tracker/?atid=619&group_id=136)...

You do use the current version [MPFR 4.0.2](https://www.mpfr.org/mpfr-current/#download) and the current [cumulative patch](https://www.mpfr.org/mpfr-current/allpatches), don't you?

**Comment by LADSoft** [comment]
@GitMensch, sorry I just now caught your comment.    Since there are potentially a couple of potential issues with MPFR, and since I'm not entirely up to date, I was going to get the latest then rebuild everything and see what issues I have left while working on #502.    If I can confirm anything for MPFR I'll raise the issue with them at that time.

Since my memory hasn't been that good lately I'll also add a note to #502.
