### ISSUE TITLE
analyze 'delete' behavior

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#474]
it has been noticed sometimes that the compiler will attempt to free memory it hasn't allocated (when compiled with itself).   there may be an issue with compiling the STL that causes this.   analyze the behavior and see if there is anything we want to do about it.

**Comment by chuggafan** [comment]
If it's only when compiled with itself then we should be looking at the behavior of free(), I'm assuming that our free() is https://github.com/LADSoft/OrangeC/blob/master/src/clibs/alloc/free.c

Turns out we also never actually inform the system if the memory we allocate is no longer in use so any applications using OrangeC will indefinitely chew through memory and even if the memory is gigabytes empty the system will not have been restored to it.

I recall there was a discussion on the malloc we use but I don't remember exactly when or where it took place, only that it took place.

**Comment by LADSoft** [comment]
yeah we will want to switch to another known allocator,  the dlea I have has had issues in the past although seems ok for the moment.    But like you say it is very old at this point...   I'm not adding anything more to the current milestone unless I have to but will add it to the next one :)

**Comment by LADSoft** [comment]
this is up next.   rpmalloc looks good so I'll probably just try it and see what happens.    If I'm really lucky it will somehow fix #528 lol

**Comment by LADSoft** [comment]
i thought adding rpmalloc was going to be straightforward, but it relies on C11 threading support and there were bugs...    still working out the kinks...   and then I still have to look into the original issue after that as it is still an issue...

**Comment by LADSoft** [comment]
I figured out rpmalloc won't work;   the fact of having separate heaps for different threads breaks common programming models...  and omake for example responds negatively to that.     Will look at finding a new replacement for lea tomorrow night.    Any suggestions?

**Comment by chuggafan** [comment]
glibc IIRC uses a modified version of http://jemalloc.net/ and FreeBSD uses it.

**Comment by LADSoft** [comment]
thanks!

**Comment by LADSoft** [comment]
jemalloc looked too intense; meanwhile I figured out I could fix rpmalloc simply by disabling the multithreading support then adding crtical sections around the allocation functions.    Will go on to look at the main reason for this issue next...
