### ISSUE TITLE
String continuations don't compile

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#487]
in:

```
char *string="this is a string\
with a continuation\
with another continuation";


```
it doesn't compile

**Comment by chuggafan** [comment]
I suspect that this is caused by a skip in the preprocessor where the backslashes aren't concatenated as according to C17 5.1.1.2 paragraph 2.

>Each instance of a backslash character (\) immediately followed by a new-line character is
deleted, splicing physical source lines to form logical source lines. Only the last backslash on
any physical source line shall be eligible for being part of such a splice. A source file that is
not empty shall end in a new-line character, which shall not be immediately preceded by a
backslash character before any such splicing takes place.

And AFAICT there is no such step being performed in the preprocessor. I'm not sure however, I do think that multiline macros work for some reason. So that is the most likely source of this error.

**Comment by LADSoft** [comment]
yeah we are on the same page, I figured it was something in the preprocessor too :).    I think it was recently broken, when we switched preprocessors.... I believe the compiler would have handled it before that!

**Comment by LADSoft** [comment]
actually it wasn't as bad as I thought...   mostly it worked, just not if you put a single-line comment marker inside the string lol!
