### ISSUE TITLE
Update ChangeLog

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#508]
Both https://github.com/LADSoft/OrangeC/blob/master/HISTORY.md and https://github.com/LADSoft/OrangeC/releases/tag/Orange-C-v6.0.45.1 miss the current entries so I'm a bit lost which of the marvelous changes I've read before are included in this version and if it marks the end of https://github.com/LADSoft/OrangeC/milestone/2 (I don't know if there's a "closed"/"finish" state for milestones@GH either).

As the current release is also not mentioned in http://ladsoft.tripod.com/orange_c_compiler.html - maybe it is only a pre-release?

Thank you for taking care.

**Comment by LADSoft** [comment]
the issue was it was going to take until late night to finish building and I wanted sleep so I pushed off finishing the release till today...   having learned from last time that if I try to finish the release documentation before the build completes it just causes headaches.   I've updated both the release and HISTORY.md now...   off to update my web page.

Git does have a way to close milestones so I'll also close that out soon.
