### ISSUE TITLE
Compiler lockup

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#541]
the following code fragment locks up the compiler:

```
int vv()
{
	int one;
	int two;
	int three;
	int four;
	int five;
	int six;
	int aa = one + one + two + three + four + five + six
	 +  one + one + two + three + four + five + six
	 +  one + one + two + three + four + five + six
         +  one + one + two + three + four + five + six
	 +  one + one + two + three + four + five + six;
	return aa;
} 

```

**Comment by chuggafan** [comment]
The problem is located in OCCPARSE, the Parser::depth function can be O(whatever, it grows by 3 each call), which is absolutely, positively, disgustingly bad, and the path that's being taken here is 100% the O(whatever, it grows by 2 each call) path, which is just as bad, and it does this near-infinitely, disgustingly long, because of the fact that it's a bunch of en_adds being done in a row....The entire thing needs a rewrite for depth() and rebalance() because they can be disgustingly bad, rebalance in particular can grow at 5 times per call. These are two functions that call eachother a lot, so when there's a lot of expressions at once, a huge amount of time is spent on them that shouldn't be spent on them.

This will likely require an entire redesign of a huge amount of time, mostly on the same level as Milestone 7.

**Comment by LADSoft** [comment]
that is an interesting observation.    FWIW the only purpose of depth() and friends is to rearrange expressions in a more balanced way to ease register allocation later on.   There may be a better way to approach the problem though, not sure on that.

**Comment by LADSoft** [comment]
I did some reach and think the efficient algorithms for balancing a binary search tree could be applied to this problem, with some modifications because of expression precedence levels...    now that you've brought it up I really think there could be a lot of improvement with minimal work.   If you would like to try go ahead, otherwise let me know and I'll work on it eventually lol.

**Comment by chuggafan** [comment]
I have no clue where to even begin tbh, I think it would be better for you.

**Comment by LADSoft** [comment]
I'm just gonna try to modify this algorithm: [Day-Stout-Warren](https://en.wikipedia.org/wiki/Day%E2%80%93Stout%E2%80%93Warren_algorithm)

the algorithm as  specified rewrites a single binary search tree by first converting it to a linked list, and then converting it back to a tree, but should be readily modifiable to do trees within trees in a non-BST context.    Trees within trees being necessary to handle precedence levels for arbitrary expression trees....

I'll get to it whenever I get past compiling the compiler with itself as I really would like to see some sort of speedup and this looks like a good pick!    Thank you for pointing it out!

**Comment by chuggafan** [comment]
Would it be smart to just do a self-balancing tree, or do we not need to perform this algorithm very often? Depending on what we need an R-B tree or something like that would be a smarter move, maybe even make a templated version of it so that we can apply it as a container for anything we do a lot of stuff like this on.

**Comment by LADSoft** [comment]
i have mixed feelings about that...   mostly expression trees are going to be small because most expressions in a program aren't all that complicated.   Although sometimes not.    But the section of code this is in is the constant evaluation section,   and there is liberal use of re-evaluating expressions for constants especially throughout the template engine...   it seems to me like a self balancing tree implementation may not be warranted especially since the tree can't be considered in totality during the balancing (again because of the precedence levels).    It would certainly be complicated to do a self-balancing tree and may not save compile time in the end...    

Meanwhile a very simple change could be made even to the existing code that might improve it, e.g. don't call 'rebalance' if nothing in the expression has changed.    Still, I'm going to advocate for writing the simple approach to see how well it does, and if we still need improvement in this area we can think about self-balancing trees later...

**Comment by chuggafan** [comment]
Fair enough here, it's just a thought, because doing a slightly expensive operation all the time vs doing a very expensive operation all the time is a clear choice, while doing a very expensive operation once vs a slightly expensive operation all the time is a less clear choice.

As with all things though: this should be profiled more after we make the original planned changes to see if it's better to do something different, there's no point in doing something that makes the problem worse, after all.

**Comment by LADSoft** [comment]
yeah we can refactor later if we need to...    the complexity of the code required to do a self-balancing tree makes me want to do it the easy way at least at first lol!   Should be a massive improvement over what we've got though, like you say it these functions just balloon rapidly right now...

**Comment by chuggafan** [comment]
It's not just these functions, there's a whole host of functions that will rapidly and easily expand at rates near-unheard of because of  the recursive element, a way to cull this would most likely be a wise choice, switching algorithms, etc. would be the best in many cases, but I am not very good at the theoreticals and implementations of CS theory, so...

**Comment by LADSoft** [comment]
i';m not so great at theory either, I have to do a lot of web searches and look up algorithms to use sigh.   Well lets take it one thing at a time, in a few days I'll have time to look at this issue so we'll start there.   I guess though we need to take inventory and see exactly how many recursion problems we have...

**Comment by LADSoft** [comment]
I think I have this worked out, will test some more tomorrow and then if ok will put it in the compiler.

**Comment by LADSoft** [comment]
mostly have it working, there are just a few issues with the same leaf nodes being reused in different parts of an expression that cause the algorithm some problems.    Will fix it soon, but meanwhile it is back to my day job!

**Comment by LADSoft** [comment]
this is going slow because the rewrite keeps highlight bugs in other parts of the compiler....   two more to go sigh.
