### ISSUE TITLE
Update Resource Compiler to skip structs, enums, prototypes

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#547]
```c
#include <windows.h>
#define COB_WITHOUT_EXCEPTIONS
#define COB_WITHOUT_JMP
#include "libcob/common.h"

// actual content referencing symbols from common.h follow
```

leads to

> common.g(799): End expected

And

```c
#include <windows.h>
#define COB_WITHOUT_EXCEPTIONS
#include "libcob/common.h"

// actual content referencing symbols from common.h follow
```

leads to

> Error D:\Dev\orangec\include\stddef.h(68): Could not open file 'ptrdiff_t;'

[common.h.txt](https://github.com/LADSoft/OrangeC/files/5503570/common.h.txt)

I think both results are wrong, aren't they? And of course, they don't happen with MSVC.

**Comment by LADSoft** [comment]
this is actually a header issue.   ORC doesn't attempt to compile c constructs such as enums, structures, or function declarations.

I'm fixing the standard headers to bracket such things with:

```
#ifndef RC_INVOKED
....
#endif

```
and external headers need the same if they are going to be included in an RC file.

Using such bracketing was an older practice, apparently microsoft has updated their RC compiler to know a little about the C language...

**Comment by GitMensch** [comment]
> this is actually a header issue. ORC doesn't attempt to compile c constructs such as enums, structures, or function declarations.

Hm, what do you think about letting it know enough to skip those?

**Comment by LADSoft** [comment]
I think I tried that at one point; it turned into a big project though.    Maybe I'll try again sometime...

**Comment by LADSoft** [comment]
i think the main holdup on this is that I can probably do it in the most specific cases with a simple struct or enum, but once you start adorning 'struct' or 'enum' labels with various qualifiers things get a little dicey because orc doesn't know the difference between those and valid names for resources...   and it is even more dicey if there would be two qualifiers before the 'struct' or 'union' tag because that would match the 'generic' resource type (which uses a user-defined resource type name).    Although I suppose I could code in every possible qualifier that occ will accept and do the qualifier check after the preprocessing is done...   that *might* work I dunno but it might limit those qualifiers from being used as valid resource names...

**Comment by GitMensch** [comment]
Because of the "possibly limiting" part: let's just go with the "easy skip" for now (maybe "from `struct`/`enum` to first `;` after first (or ideally "matching" `}`) - this should solve the most issues and wouldn't prevent any other use, would it?

**Comment by LADSoft** [comment]
let me take a step aside from what I'm doing and see if I can get that much working reliably :)

**Comment by LADSoft** [comment]
im going to check in a version that handles structs, enums, typedefs, but not function prototypes...

**Comment by LADSoft** [comment]
i had figured out I could make it at least a little more generic, right now the only problem I know of is that you cannot have multiple qualifiers before a struct/union tag.    It does parse cobcrun.rc with the #include <gmp.h> added...
