### ISSUE TITLE
Make different configurations for include paths for C++ and C compiles

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#562]
The default system include path should change depending on whether it's a C++ or a C compile so that C++ files don't get included when we're in C mode.

I believe both GCC and CLANG follow this behavior, and I have no idea if MSVC does as well, presumably with their new C18 support they don't, but I don't know.

**Comment by LADSoft** [comment]
hmmm will have to think about how to approach this.    Don't think we can just add a new config file since c and C++ files can be intermixed on the command line and the config files are parsed before any of those are considered.    Maybe it would work if I just assume that if there is a system path specified I can skip the first element of the path in C mode.   (it would be passed into the preprocessor that way thus wouldn't affect the preprocessor code it self)

**Comment by chuggafan** [comment]
Maybe we can have a way to internally mark a code section as being C++ system path specific? Maybe a /Z and a /z? I know the way GCC does this is that G++ and GCC are two entirely separate executables with different search paths, I think *MAYBE* clang also does this? I doubt it, and I don't know that much about clang's behavior.

**Comment by LADSoft** [comment]
hm that is a good idea.    I will add it soon...
