### ISSUE TITLE
Should occ ignore -fPIC?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#623]
As far as I see there's no use for a compile flag like this in occ, is there?
I'm not sure, but as this option is partially hard-wired in existing makefiles - should occ simply ignore this or should the makefiles be fixed?

**Comment by LADSoft** [comment]
I'm not sure where you are seeing this?   I can ignore it if you like,  as there is no easy way to do PIC on the x86...

**Comment by GitMensch** [comment]
> I'm not sure where you are seeing this? 

Different makefiles originally created for GCC, often MinGW.

>  I can ignore it if you like, as there is no easy way to do PIC on the x86...

Hm, maybe "implement" it in a way that x86 builds will ignore it silently and x64 will do something with that someday?

Note: I'm _not_ sure about the question "Should OrangeC ignore this or should the Makefiles be adjusted". At least for the some I've tried `-fPIC` was the only not-implemented option so far.

@chuggafan Do you have an opinion here?

**Comment by chuggafan** [comment]
I'm going to be quite honest and say though I know Position Independent Code as a flag exists, I have never myself known what the difference is, presumably it has something to do with when you import libraries via LoadLibrary vs have static references but I would not know at all.

**Comment by LADSoft** [comment]
PIC code is designed in such a way that it can be loaded into memory, without need for the OS to go applying fixups.    For example on x64 you have instructions so you can reference constants and data similarly to how jumps and calls are done on the x86, e.g. there are pc-relative indexing modes.   Another possibility is use an index register to access constants and data, and never use direct memory locations hardcoded in the exe file.    That takes a little care to do because addresses you can put in the exe file data section for a non-PIC program have to be calculated at runtime in a PIC program...   (this is really just deferring the fixups to the program instead of the OS, but usually there are a lot less of them when you do it this way)    But that uses up a register basically to hold an address which will basically be constant throughout the life of the program.

On x86 such things don't make a whole lot of sense due to lack of addressing modes and small register bank size, although you could pull it off if you want.   But on x64 and other architectures you've got the pc relative indexing modes and you've got plenty of registers, so you can pull it off relatively easily.    I think win64 requires PIC if I'm not mistaken...
