### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#634]
I means how standard compliant it is. Does it still use STLport as it standard library? I saw there are many tests regarding libcxx (it's the same as libc++ from LLVM, isn't it?). Does the project switched to use libcxx as the standard library now?

**Comment by LADSoft** [comment]
STLPort is long gone.   In earlier times when I was using it, i found it somewhat buggy and subsequently switched to libcxx.   So we have used libcxx as a standard library for a long time now; we recently switched it to use libcxx version 10 (from version 8) and added threading and atomic support.   That required a lot of improvements to type aliasing as it brought in new code that specifically targeted C++14...  the initial implementation of type aliasing in occ was somewhat lacking...    

Yes libcxx is the LLVM library.    We try to use it as is but there are some parts such as exception handling where we still use a home-grown approach.    The other notable one is the typeinfo header which is still home-grown.   Just recently (within the last week or so) I did switch out and start using the libcxx initializer_list header and got rid of our home grown one...    you can see the complete list of home-grown headers in \orangec\src\clibs\cpp\stdinc_libcxx.   It isn't too bad at this point...

We are just starting on running the libcxx tests through OrangeC recently, there are issues but we are slowly working through them.    The libcxx tests are fairly comprehensive and OrangeC will be much improved when we complete that task.    But it is a fairly large task (there are around 5300 tests to get right) so this will likely take a little while.   Once we get all the tests working we'll add something to the automatic builds to run through them regularly...

I am just finishing up revamping the constexpr function support as a result of the tests, it is much better now.   Not that the compiler didn't functionally work before, it just didn't take all the opportunities it could to evaluate constexpr functions at compile time.    But doing that properly is one of the requirements of the tests so I had to bite that bullet now rather than later.

As far as standards compliance in general, we try to keep up with the latest standard we are targeting (which happens to be C++14 right now) but there isn't any way to enforce older versions of the standard...

**Comment by GitMensch** [comment]
As the answer is answered and the original user asking it was deleted I suggest to close this one.

**Comment by LADSoft** [comment]
the only reason I left it open was in case someone else wanted to read it lol.
