### ISSUE TITLE
How to use Coff2IEEE

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#640]
After looking at https://github.com/LADSoft/OrangeC/blob/master/doc/general/Coff2IEEE.md I've thought that I can use an import lib created by MSVC to convert it to OrangeC import libraries.

So I've taken the ones found at https://ci.appveyor.com/api/projects/GitMensch/gnucobol-3-x-vs/artifacts/dependencies-x86.7z?job=Image:%20Visual%20Studio%202019;%20Configuration:%20Release;%20Platform:%20x86 in lib directory, then did

~~~
$ coff2ieee -ozlib.l zlib.lib
coff2ieee (OrangeC) Version 6.0.50.236
Copyright (C) LADSoft 2006-2021
converting library file
failed
~~~

Where have I gone wrong?

Side notes:

1) it seems there's a `\n` missing after failed, if I execute two commands like this in a row I get

~~~
Copyright (C) LADSoft 2006-2021
converting library file
failedcoff2ieee (OrangeC) Version 6.0.50.236
Copyright (C) LADSoft 2006-2021
converting library file
failed
~~~

2) instead of "converting library file" an output of "converting library file zlib.lib" (maybe with full path) would be reasonable.

**Comment by chuggafan** [comment]
I think coff2ieee only works on actual COFF files, .lib are static libraries IIRC and a completely different format.

**Comment by chuggafan** [comment]
Work on the drop-in library looks good, I will probably throw up a new repo entirely for it as I plan on it being able to be used outside of any specific project, when that happens I'll throw a link here, and I'd like some feedback as I'll probably work on it for quite awhile as the COFF spec is a pretty hefty thing and parts of it are really, really poorly defined.

**Comment by GitMensch** [comment]
If you don't know of those yet you may want to have a look at https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-tools/ - at least genlib is COFF related.

**Comment by chuggafan** [comment]
My source has been a word document entitled pecoff_v8 atm, it's been good, though lacking a bit of documentation, and is effectively the same thing as the official online microsoft documentation.

The first issue of getting parsing of static libraries is done, the secondary thing of getting PE files and DLLs parsed is whatever but will be worked on. The main thing I want out of a redesign is being able to utilize the 3rd linker member for accurate names.

**Comment by LADSoft** [comment]
thanks for taking this on!

**Comment by chuggafan** [comment]
Update: got more than one file working (at least for the first three members, the easiest portion to actually parse and verify since dumpbin works on it...)

```
Archive member name at C2: //
6189E1CB time/date Mon Nov  8 21:49:47 2021
         uid
         gid
       0 mode
      25 size
correct header end
```
vs my tellg debug setup:
```
1
First: 1
92
Second: 1
189
Third: 1
```

The docs I'm 99% sure say we need to be aligned on a 1-bit boundary (n % 2 == whatever).
All of this is done *AFTER* the alignment... if it's needed at all, that is....
Sometimes it demands alignment
So location 1 happens at location 9, 189 is ??????? and sometimes this stuff happens whatever, as shown here:

```
9
First: 1
200414
Second: 1
397218
Third: 1
```
^ VS2022 Coff2Ieee.lib on my changes

And another example:

```
C:\OrangeC\static_library_parser>parselib.exe ..\src\lib\ms\dlpe.lib  
9
First: 1
305001
Second: 0

/               1636426187              0       301337    `
```
^ that indicates that we grabbed something 1 too early, meaning we needed to skip 1...

W H Y

*bangs head against docs*

**Comment by chuggafan** [comment]
*Apparently* tellg was lying to me about it's location somehow or I read things wrong... not particularly happy with how this is going now :/ Looks like a true cleaning house in my code will have to happen since I *am* abusing certain things in code...

**Comment by chuggafan** [comment]
I actually figured out my issue: Turns out that when you're not in binary read mode funky stuff goes on in-code for no apparent reason whatsoever...
Dunno why, but it does, probably has to do with CRLF -> LF conversion in line endings or something else funky happening....

I'll throw the code up probably later tonight so that you can judge what I've been doing so far, I *THINK* it's ok, but COFF parsing (rather than just parsing the lib) is currently not completely supported.

**Comment by chuggafan** [comment]
https://github.com/chuggafan/COFFParser Here's a link to what I have so far, I'm liable to forget that this project will exist, I do want as much info about how I've been doing things so far though, but I think for beginning a project like this it's OK, I've gotten the first 3 linker members to consistently be parsed along with all the info contained within...

**Comment by LADSoft** [comment]
yeah if not in binary mode on windows, CRs get stripped out before the program sees the data so you actually lose data.   That is why the tellg was off too...

**Comment by LADSoft** [comment]
closing
