### ISSUE TITLE
issues with [[noreturn]]

### ISSUE THREAD

**Issue by LADSoft** [LADSoft/OrangeC#651]
in #635 it was discovered that the microsoft compilers allow [[noreturn]] on functions that don't return void....    ORANGEC basically uses the same code to error check both the C and C++ style NORETURN tags.   ORANGEC is generating an error if the return type isn't void.   I *think* the C style NORETURN is spec'd to have to return VOID though...   we need to look at what is supposed to happen for the two NORETURNS as well as what other compilers commonly do, and determine if we want to make a change to ORANGEC to accomodate this.

**Comment by chuggafan** [comment]
The noreturn isn't spec'd in C to always be VOID:
```
A function declared with a _Noreturn function specifier shall not return to its caller.
Recommended practice
The implementation should produce a diagnostic message for a function declared with a _Noreturn
function specifier that appears to be capable of returning to its caller.
```

https://files.lhmouse.com/standards/ISO%20C%20N2176.pdf

On page 110 (of the PDF).
This seems consistent with the C++ del.attr.noreturn section where it just says "produce a warning" instead of a diagnostic. What we can do is for functions whose body is visible but aren't void we can check to make sure all code paths are using noreturn (throws or calls a noreturn function) and throw a warning otherwise and throw a warning on any function that has a return type other than a void return that is noreturn.

**Comment by GitMensch** [comment]
Sounds good, but as you may need a function passed as a parameter / assign it to a variable I'd do nothing about the return type `void` would be as fine as `int` [example: 20 functions matching `int (char *, char*)` and only one of this is _noreturn_ - because it would be a fatal error exit _if_ this is called], there should no need to change this to void and create an int wrapper function.
