### ISSUE TITLE
Analyzer should not complain about a function not returning a value if the function calls a noreturn function

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#655]
```
Warning(105)  c:\orangec\src\clibs\cpp\libcxx\include\exception(182):  Function should return a value
note:         c:\orangec\src\clibs\cpp\libcxx\include\exception(168):  Referenced in instantiation of 'std::make_exception_ptr<future_error>(future_error)'       
note:         c:\orangec\src\clibs\cpp\libcxx\include\future(1379):  Referenced in instantiation of 'std::__1::promise<int>::~promise()'
note:         C:\OrangeC\src\clibs\cpp\libcxx\test\std\thread\futures\futures.shared_future\ctor_future.pass.cpp(27):  In template instantiation started here  
```

This appears when the function itself isn't marked noreturn (because if the function is marked noreturn all instances, and the function isn't a main function, it automatically with error out with either a proper error (function returning reference should return value) or a warning (FUNCTION_SHOULD_RETURN_VALUE), what we should do it analyze if all code paths end in either a noreturn function call or a return, and *THEN* error. I don't know how to smuggle this information into the code at this moment in time...

**Comment by chuggafan** [comment]
I found a way to smuggle this information using blockStmt and looking at the tail, however this isn't effective and each block should theoretically be checked for each block and each block's tail(?) should be checked if all of them are either returns or calls to a noreturn function. I will likely look at this tomorrow as a way to continue looking at this.

**Comment by LADSoft** [comment]
im not 100% sure, but the intent of the existing code may be to handle this properly.   At issue is the 'needlabel' member of the blockdata statement.   Theoretically, if you get to the end of a function and needlabel is false that means the function can return without a return statement...   because needlabel is intended to catch the case where the next block in the sequence won't be reached without the existance of a label (for reference by a goto).    

Looks like noreturn functions calls are caught in statement_expr and needlabel is set there... and if it is propagated correctly and there aren't other ways to get to the end of the function without setting needlabel it should result in no error...   but... it looks buggy for nonstatic member functions as in that case the en_func will be wrapped by an en_thisref...  might work for static member functions and free-standing functions though...
