### ISSUE TITLE
Is `occ -c` intentional different from `occ /c`?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#67]
`occ -h` is identical to `occ /h`, same for `occ -I` and `occ /I`.
I *guess* `occ -c` should be identical to `occ /c`, shouldn't it?

Using current CI version `occ -c` invokes `olink` after creating the object file...

**Comment by LADSoft** [comment]
actually there is an intentional difference...   many moons ago when I started this project I meant for command line switches started with a '+' to mean positive application of the switch, or '-' to mean negative application.   Later I added '/' which also meant the positive application.   I do realize though that this is totally different than how any other program on the planet works...  (including all the other tools in the same toolchain).   The idea is that if ever I get around to rewriting the compiler in C++ I would use the same framework used by the other tools which means it would be more 'normal'...   but maybe I ought to go ahead and fix it now?

**Comment by GitMensch** [comment]
Rewriting the command line options will help both for users that don't know of the current behavior and me for testing OrangeC.

But a changed design of command line evaluation screams for broken build scripts...

I therefore suggest to do the following:

* either: create an additional frontend for occ that calls it internally - but uses the same framework olink has (call it orangec for example, or occc, or ...) - this just takes the command line options, convert if necessary and calls occ
* or: implement two command line parsers in occ, using the old/new one depending on an environment variable (`POSIXLY_CORRECT` is often used for GNU/Linux command line options for similar reasons, maybe `OCC_OPTIONS_LEGACY` could be used) - if you do this without bumping the version number it likely is better to default to the old behavior and use something like  `OCC_OPTIONS_COMMON`) and clearly note the result and reasons for it in `occ /h`

**Comment by LADSoft** [comment]
it was easiest just to change the interpretation of '-' to make it the same as '/' and defaulted to the new behavior.   I did add an environment variable 'OCC_LEGACY_OPTIONS' which if it exists will force the old behavior.
