### ISSUE TITLE
LibFIles::ReadOffsets not having the count be the same as files

### ISSUE THREAD

**Issue by chuggafan** [LADSoft/OrangeC#684]
I've been recently having an error where the assert for `LibFiles::ReadOffsets` in LibFilesLinker.cpp has been failing for an unknown reason, normally only occuring when using one of the `*compiles.bat` systems, I'm partially inquiring as  to if anyone else has noticed this  and if there's any easy way to debug what or where the root cause can be, if need be I'll bisect the *entire git repository* for this.

**Comment by LADSoft** [comment]
i saw something weird the other day, but I don't know where it was or what it was, and when I tried to replicate it the problem went away.   That was when using the BUILD.BAT script.

count has to match files.size();

files is populated in ReadNames() in the same file.   So that is what count has to match...

ReadNames and ReadOffsets are called in sequence like this:

``` c++
    if (!files.ReadNames(stream, header.filesInModule))
        return false;
    if (fseek(stream, header.offsetsOffset, SEEK_SET))
        return false;
    if (!files.ReadOffsets(stream, header.filesInModule))
        return false;
```

so that kinda indicates that either the header structure is getting corrupted somehow so that the 'count' argument for the two calls doesn't match, or there is bad code generation for one of those two functions...    maybe some printfs would clarify which is happening...

**Comment by chuggafan** [comment]
This issue appears to have been resolved between commits 0c8b6e0496b574764129db49e7d812729bb78644 and 41f715d40e8ea50f96082fc120d71a21663a6ebd

I will investigate likely next week which commit it was so I can figure out what went wrong because it's working and nothing seems to have touched it

**Comment by GitMensch** [comment]
git bisect

should find the issue for you most easily.

**Comment by LADSoft** [comment]
any news on this?

**Comment by chuggafan** [comment]
I honestly completely forgot about this. I don't think I see the issue anymore but I haven't tested much lately as I've been focusing on implementing `#embed` slowly but surely

**Comment by LADSoft** [comment]
ok.   I forgot you were working on #embed...

**Comment by LADSoft** [comment]
Im going to close it, please reopen if the issue resurfaces.
