### ISSUE TITLE
trunk/src/clibs/stdlib/atof.c:173: strange expression ?

### ISSUE THREAD

**Issue by dcb314** [LADSoft/OrangeC#707]
Source code is

        if (*ch == 's' && *ch == 'S')

Maybe better code:

        if (*ch == 's' || *ch == 'S')

**Comment by GitMensch** [comment]
Would you mind to use the "edit" function which will fork this repo for your account and create a pull-request with the change? This way your reasonable and very useful findings can be integrated much faster (and also easier peer-reviewed).

Also: when you are done here I'd would know another project which you could have a look at...

**Comment by dcb314** [comment]
>Would you mind ...

Yes I would mind. I find bugs, the developers fix them. Sorry.

BTW, does Orange C compile on Linux ? I have some stronger tools there.

>I'd would know another project which you could have a look at

Please let me know. I used cppcheck, my favourite static analyser.

**Comment by GitMensch** [comment]
> Please let me know.

https://sourceforge.net/p/gnucobol/code/HEAD/tree/branches/gnucobol-3.x/ ready to compile tarballs (= does not need maintainer tools) and even windows source ".zip" (= VC + OrangeC via OCIDE) available at https://sourceforge.net/projects/gnucobol/files/gnucobol/nightly_snapshots/ bug reports welcome at https://sourceforge.net/p/gnucobol/bugs.

> I used cppcheck

Used that via command-line and plugin-integration to VC, but that's been a while.
False-positives are always a hard thing to tackle, otherwise this could run in the CI and "fail" builds and PRs when there are errors found. This somehow reminds me of #654 (and that it would be a good idea to run GnuCOBOL there again).

**Comment by LADSoft** [comment]
@dcb314 thank you for your efforts.

 occ compiled on linux at one point although it didn't actually run.    Unfortunately we lost travis ci so I haven't been able to validate that...

**Comment by LADSoft** [comment]
fixed in 85738fd79a9c90fd6c4e473ea3f31860199925f0
