### ISSUE TITLE
Legal issues if we take and use Pelles C's Windows API headers?

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#715]
I don't know anything about this stuff. But Pelles C's Windows API headers is the most simple I have ever seen. I think it will easier to start with them than porting from MINGW64. Perhaps you could try asking permission from Pelle. He is on the Pelles C forum (https://forum.pellesc.de/), for some unknown reasons I can't access this forum, it seems my ip address was banned. How ridiculous! IP address is dynamic and I'm sure I didn't do anything at their forum!

This is Pelles C: http://www.smorgasbordet.com/pellesc/

Support for these headers could be either we patched them to check for `__ORANGEC__` instead of `__POCC__ `(is it right? I don't know how OrangeC defined itself but I guess `__ORANGEC__`), or we define `__POCC__` ourselves as part of OrangeC. The `__POCC__` version should be lower than 500? As it seems OrangeC doesn't support `#pragma once` (same as MINGW64).

**Comment by LADSoft** [comment]
I took a brief look at this, yes it looks like with some minor massaging these headers would be easier to manage than the ones out of mingw64....   almost a drop-in replacement for what we've already got and probably much better quality...

the licensing seems to be doing anything you want just don't sell it kind of licensing,  I can't remember if he wanted to be mentioned in the docs but I always mention where stuff I reuse came from anyway...

I'll look closer at this soon...

**Comment by 3oheicrw** [comment]
@LADSoft this issue should be closed.

**Comment by 3oheicrw-alter-ego** [comment]
> I took a brief look at this, yes it looks like with some minor massaging these headers would be easier to manage than the ones out of mingw64.... almost a drop-in replacement for what we've already got and probably much better quality...
> 
> the licensing seems to be doing anything you want just don't sell it kind of licensing, I can't remember if he wanted to be mentioned in the docs but I always mention where stuff I reuse came from anyway...
> 
> I'll look closer at this soon...

You are too good man. MinGW just said their headers are public domain from various sources. Pelles C is the same even though he doesn't use the public domain license like MinGW. He collects his headers from various sources, including the Windows SDK itself. If I was you I will not said the headers come from Pelles C but instead make them public domain license and put a statement that they are from various sources use with your own risks like MinGW. Because you patched the Pelles C headers to work with OCC but not using the vanilla headers, they are different enough to the original Pelles C headers, if you don't tell it no one will know you take them from Pelles C, think will only know you assembled them from various sources like MinGW!

MinGW headers, frankly speaking, is the product of thief. So does Pelles C headers.

BTW, it's not for no reasons that people called the GPL as cancer because it does really spread. It's sometimes very ridiculous. Take this into account. The original Pelles C headers is, e.g: Pelles C license. But you have to patch it to use with OCC, your modifications could be licensed under the GPL unless you explicitly state it's under another license of your choice. Let's assume you put it under GPL, so the final combined works, the headers, will be covered by the GPL or original Pelles C license? It's so easy to interpret it's also under GPL because without the GPL modifications it will not work with OCC!

GPL derivatives and GPL compatible licenses, all of these concepts are also of the thieves. GPL is the license of the thieves. You can legally steal the works of other by putting a think GPL covered modifications ontop of the original license then the final product will be covered by the GPL! The FSF will only have to said the original license is GPL compatible. There are no clear rules to define whether a license is GPL compatible or not, it's just by the mouth of the FSF dictators that dictated it's compatible or not, and you will be able to legally steal the works covered by it or not!

GPL worshipers on phoronix always praised GPL protection by the mechanic of GPL spreading like cancer and GPL forced derivatives to also GPL. People on the FreeBSD forums like us hated the GPL because we view it's a tool of thieves!

p/s: it's too off topic, sorry. But my point is, GPL is already the license of thieves, and you are legally to steal, why don't just doing like the MinGW people? Why do you have to give credits to the Pelles C people? It will very risky if someday he popped up and said your usage of his works is illegal. You will have to remove all of it and roll back to your previous version of headers. Just doing like the MinGW people, said it's public domain and from various sources. Done.

**Comment by GitMensch** [comment]
In my opinion: That is nonsense.

Even when Pelles used various sources (I didn't check that), then attribution is always a reasonable thing.
The question of: Is this GPL compatible has clear rules (mostly: are derived works, especially under a different license, possible) - and it would need a check if they are.

I'm any case I'd suggest to have the headers LGPL if the runtime library is LGPL (or GPL with a linking exception), or, if the original license is public domain keep it that way

**Comment by 3oheicrw** [comment]
> I'm any case I'd suggest to have the headers LGPL if the runtime library is LGPL (or GPL with a linking exception), or, if the original license is public domain keep it that way

You have the same idea as me: https://github.com/LADSoft/OrangeC/issues/680

**Comment by LADSoft** [comment]
Yeah I'm on the side of attributing things too.   A lot of work goes into this kind of software and there is no way I'm going to just steal it.

I had thought I had updated the license files to reflect the Pelles/LCC licenses and the fact that the windows headers are NOT covered by the GNU license like the rest of the software but instead followed the original licensing, however, that slipped through the cracks again.   It will be in the next push (hopefully later this weekend).

**Comment by LADSoft** [comment]
this is done
