### ISSUE TITLE
Pelles C's C runtime library

### ISSUE THREAD

**Issue by ruanjiasing** [LADSoft/OrangeC#720]
They are on `C:\Program Files\PellesC\Lib`, the single threaded version is crt.lib and crt64.lib, the multithreaded version is crtmt.lib and crtmt64.lib. I have a weird idea: what about using Pelles C's runtime library with OrangeC? OCC supports `-nostdinc` and `/z` so what about using Pelles C's C standard headers too?

**Comment by 3oheicrw** [comment]
@LADSoft @GitMensch @chuggafan What do you think about it?

**Comment by LADSoft** [comment]
yeah  C2X is already on the roadmap; the main thing stopping it is the C++ work currently being done.   As far as other C standards we should be mostly up to date...   I hadn't thought to go through and add all the microsoft extensions although I think there is already an issue to add the posix extensions....    I'll look into it when I get a chance...

**Comment by 3oheicrw** [comment]
> yeah C2X is already on the roadmap; the main thing stopping it is the C++ work currently being done. As far as other C standards we should be mostly up to date... I hadn't thought to go through and add all the microsoft extensions although I think there is already an issue to add the posix extensions.... I'll look into it when I get a chance...

Frankly speaking I'm thinking Microsoft extensions is a misery for me. On Pelles C, when you ever include the Windows API headers, you are forced to turn on Microsoft extensions. Otherwise, you will face this very annoying error:

https://forum.pellesc.de/index.php?topic=4083.0

I don't care about the Microsoft extensions. The document about them on Pelles C help file caused me to think they are not really important. I don't think MinGW supports them. But I'm not sure about that. I can't find the relevant information. On Google, if you searched for "mingw microsoft c extensions", it will give you useless results about Visual Studio Code and it C/C++ plugin (they called plugin as extension).

I only want a better C standard headers and of course a better Windows API headers, I don't want to carry the quirks of Pelles C to OrangeC. IMO GNU extensions (that you called POSIX extensions) is more important and should have than Microsoft extensions. Microsoft extensions is for an outdated C version. MinGW could compile Windows API applications just fine without it.

**Comment by LADSoft** [comment]
I'm working on adding most of the 'private' functions from Pelles C.    Reimplementing rather than reusing.  Some of the programs you gave me to build require them anyway...

**Comment by LADSoft** [comment]
I added a bunch of functions, including the statxxixx functions and other functions required to run some of the programs that I was asked to fix
