### ISSUE TITLE
Build failed with MSYS2's CLANG64

### ISSUE THREAD

**Issue by ghost** [LADSoft/OrangeC#728]
MSYS2's CLANG64 bin directory added to Windows PATH.

Since there is no support for Clang/MinGW yet https://github.com/LADSoft/OrangeC/issues/727, I reuse MinGW64 target of OMake https://github.com/LADSoft/OrangeC/issues/724:

`omake -DCOMPILER=MINGW64 fullbuild`

Build failed. I can only capture the last error in this screenshot.

![2e](https://user-images.githubusercontent.com/116574529/198210048-ec818e87-9ae8-4f37-b73a-1b51394617d0.PNG)

**Comment by 3oheicrw-alter-ego** [comment]
I don't care anymore. Gave up.

**Comment by LADSoft** [comment]
so the reason this fails is that the make files use the windows version of CLANG but that requires access to the MSVC link and lib programs.   

Putting those on the path seems to make it work...

a better solution would be to use the native version of clang along with ar and ld, however, there is still a lot of dependency on WIN32 in the sources, it hasn't been adjusted to actually generate working code for linux even though last time we tried it did at least compile on linux.

I also got lost trying to figure out how to configure clang to find appropriate headers and libraries in msys2, so for now I'm going to let this go.

**Comment by ruanjiashing** [comment]
> so the reason this fails is that the make files use the windows version of CLANG but that requires access to the MSVC link and lib programs.
> 
> Putting those on the path seems to make it work...

Yes, your [clang.mak](https://github.com/LADSoft/OrangeC/blob/master/src/clang.mak) only accounts for LLVM/MSVC so it will only works if MSVC installed. See: https://github.com/LADSoft/OrangeC/issues/727

> a better solution would be to use the native version of clang along with ar and ld, however, there is still a lot of dependency on WIN32 in the sources, it hasn't been adjusted to actually generate working code for linux even though last time we tried it did at least compile on linux.

No. You don't need to do anything special. Just re-use [mingw64.mak](https://github.com/LADSoft/OrangeC/blob/master/src/mingw64.mak) for building with LLVM/MINGW. The only changes I suggest is on line 72 with COMPLIB you shouldn't put `-lstdc++` there as the default C++ standard library will be linked anyway unless you said it to not and I think you didn't do anything like that. Why I suggested this? Because the standard C++ library on MSYS2 CLANG64 environment is `libc++`, it doesn't ship with `libstdc++` like the LLVM/MINGW of winlibs.com.

I would separate LLVM/MINGW into two smaller subsets:

First is LLVM/GNU-MINGW, this is like the winlibs.com distribution, it offers LLVM Clang build against GNU-MINGW environment, which is using `libstdc++` (`libc++` doesn't included) and GNU binutils.

Second is LLVM/LLVM-MINGW, this is like the MSYS2 CLANG64 environment and the distribution here: https://github.com/mstorsjo/llvm-mingw, which is using `libc++` (`libstdc++` doesn't included) and LLVM Tools instead of GNU binutils.

> I also got lost trying to figure out how to configure clang to find appropriate headers and libraries in msys2, so for now I'm going to let this go.

MSYS2 provides you 5 shells. Each shell has different icon and you could find them from Start Menu. First is vanilla MSYS2 Shell, it's very similar to Cygwin. Second is MINGW32 Shell. Third is MINGW64 Shell. Fourth is CLANG64 Shell. Finally is UCRT64 Shell. You don't have to care about UCRT64 Shell, it's just MINGW64 but links to UCRT instead of MSVCRT, as OrangeC doesn't support UCRT anyway (or does it? See: https://github.com/LADSoft/OrangeC/issues/734).

What you wanted is the CLANG64 Shell. The CLANG64 Shell already has everything setup for you. The build environment is ready with symlinks created to make it appear as a GNU GCC compatible environment, for example, `cc` and `gcc` symlinks are created and they are both point to `clang`, you could verify it by running `gcc -v`, symlinks are also created to fake a GNU binutils environment but they are indeed both GNU binutils but LLVM Tools being used (`ld` is `lld`, `ar` is `llvm-ar`,...).

Please note that the MSYS2 CLANG64 environment also default to UCRT runtime instead of MSVCRT. Take this in caution.

You could download a LLVM/LLVM-MINGW that links to MSVCRT instead of UCRT from this project: https://github.com/mstorsjo/llvm-mingw/releases But doing so I suggest you to use a normal Windows Command Prompt environment than MSYS2 as it will save you a lot of headache. It's simple, just download the archive and unpack it, add the bin directory to PATH and started to build using [mingw64.mak](https://github.com/LADSoft/OrangeC/blob/master/src/mingw64.mak) just like you are using a normal GCC based MinGW.

**Comment by ruanjiashing** [comment]
Almost forgot, let's assume I'm talking with someone has never used MSYS2. The first thing you need to do after installed MSYS2 is to update it, doing `pacman -Syu` and follow the instructions on the screen and keep issuing this command util it said there is nothing to upgrade anymore. The second thing is to installing toolchains. MSYS2 doesn't include any toolchains by default.

Install MinGW-W64: `pacman -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-make`

Install Clang64: `pacman -S mingw-w64-clang-x86_64-toolchain mingw-w64-clang-x86_64-make`

If you need git, install git: `pacman -S git`

Remember to open the respective shell, MINGW64 Shell for MinGW-W64, CLANG64 Shell for Clang64.

**Comment by LADSoft** [comment]
yeah one of the few things I know about msys2 is that I have to use pacman lol!   I will review all this later and rework the build files with some of your suggestions.    I'm going to work on my other project for a few days though so I can make some headway on that....

**Comment by iahunq** [comment]
@LADSoft This issue could be closed.

**Comment by LADSoft** [comment]
thanks.
