### ISSUE TITLE
Repeated instructions

### ISSUE THREAD

**Issue by sdkljd** [LADSoft/OrangeC#741]
OCC 6.0.61.9

![1](https://user-images.githubusercontent.com/116957851/198833173-43026c22-6c40-45f7-9fff-e6186aeeb674.png)

**Comment by sdkljd** [comment]
OCC 6.0.61.1
/O2
![2](https://user-images.githubusercontent.com/116957851/198833363-5a24bfc1-cd63-47d5-8a53-674985ef4337.png)

**Comment by LADSoft** [comment]
could you show me the line of code that generated that?

**Comment by sdkljd** [comment]
@LADSoft 
example
[ttt.zip](https://github.com/LADSoft/OrangeC/files/9895881/ttt.zip)
![000](https://user-images.githubusercontent.com/116957851/198879933-d25f93f5-e092-410c-aae6-2f1ef2c0b288.png)

**Comment by sdkljd** [comment]
![2](https://user-images.githubusercontent.com/116957851/198882809-d9ac08a0-a2be-4f89-8fd7-5ba5769610c6.png)
![3](https://user-images.githubusercontent.com/116957851/198882811-3dbc4cbc-cf7c-4e40-b831-0af90b5cec18.png)

**Comment by chuggafan** [comment]
Can you show a before/after call that shows what the stack pointer looks like? It could be a nonintuitive Calling Convention issue, I'll try to take a look if I have time this week if @LADSoft doesn't get to it first

**Comment by LADSoft** [comment]
Since @chuggafan didn't get to this I'll start looking at it.    Thanks for giving the sample, however, it seems like with just that little bit of code in a file by itself the issue doesn't appear (at least I can't find it by compiling via assembly).    Is there more code in this file you could share?    There may be an interaction between previous code and this code somehow.

If not can you tell me is this a C program or a C++ program?   What headers did you include?   What command line switches did you use to compile this?    That will help me get a little closer maybe.

**Comment by sdkljd** [comment]
@LADSoft 
All documents
occ /O2  build
+
occ /O2 /S outputs ASM
[2.zip](https://github.com/LADSoft/OrangeC/files/9947383/2.zip)

**Comment by sdkljd** [comment]
does not work on XP systems,
Hint missing GetLargePageMinimum

**Comment by LADSoft** [comment]
ok on the first issue I think the problem is you are looking at code out of the runtime library.   I think there is probably an array right before your string, and the array is empty.   Probably something to do with C++ startup code if I had to guess.

To be sure you can do this:

occ /O2 /pl-mx 2.c

and that will create '2.map' which lists all the functions in the program along with their addresses.   Search for 'main' and see where it is then you can go into your debugger and look at that address to check to make sure the code looks good.
