### ISSUE TITLE
Unable to compile Wren

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#750]
https://github.com/wren-lang/wren

It compiled fine on MSYS2 MINGW64 Shell.

**Comment by ruanjiashing** [comment]
Place this build.bat on the root directory of your Wren source tree:

```
@ECHO OFF

SET WREN_ROOT=%~dp0

SET INCS=/I%WREN_ROOT%\src\include /I%WREN_ROOT%\src\optional /I%WREN_ROOT%\src\vm

SET OPTIONS=/DNDEBUG

occ /! /c %INCS% %OPTIONS% %WREN_ROOT%\src\optional\*.c

occ /! /c %INCS% %OPTIONS% %WREN_ROOT%\src\vm\*.c
```

It's a very bad translation of makefile but it's enough for our purpose.

This is the error messages:

```
C:\Users\Administrator\Downloads\wren-main\src\optional\wren_opt_meta.c
C:\Users\Administrator\Downloads\wren-main\src\optional\wren_opt_random.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_compiler.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_core.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_debug.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_primitive.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_utils.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_value.c
C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c
Error(147)    C:\Users\Administrator\Downloads\wren-main\src\vm\wren_opcodes.h(16):  Expression syntax error
Warning(105)  C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c(896):  Function should return a value
Error(437)    C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c(920):  Invalid use of type 'int'
Error(437)    C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c(923):  Invalid use of type 'int'
Error(437)    C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c(924):  Invalid use of type 'int'
Error(437)    C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c(1386):  Invalid use of type 'int'
Error(437)    C:\Users\Administrator\Downloads\wren-main\src\vm\wren_vm.c(1390):  Invalid use of type 'int'
6 Errors
```

**Comment by GitMensch** [comment]
Just a quick check https://github.com/wren-lang/wren/blob/main/src/vm/wren_opcodes.h has `OPCODE(CONSTANT, 1)`;

which is defined as

```
  #if WREN_COMPUTED_GOTO

  static void* dispatchTable[] = {
    #define OPCODE(name, _) &&code_##name,
    #include "wren_opcodes.h"
    #undef OPCODE
  };
```
  
which is again #201 and because this extension is not available yet and the repo defaulting to computed gotos instead of defaulting to standard C in https://github.com/wren-lang/wren/blob/4d1d0d972efffd072f6a7baa5c37f312258c3955/src/vm/wren_common.h#L38-L45 does not compile.

I suggest to again adjust the define there and then likely see it working, so you can close this issue as duplicate.

Note: this and all the other issues were just quick checks with the GitHub search, please check for such issues before creating more or less the same issue again.
Note: if you care about those samples then you may want to open an issue about "computed goto should not be the default, but selected based on compilers known to support it" (which possibly is GCC only...)

**Comment by ruanjiashing** [comment]
@GitMensch The problem is, I can't patch the Wren code to compile with OCC, it's out of my ability. You said the issues are duplicated. Yes, it's right. Since other languages I submitted are actually derived from Wren. So it's nothing strange they have a common issue.

**Comment by GitMensch** [comment]
You can open an issue in their repo for changing the default and definitely can send a PR by clicking "edit" in this for and add the OrangeC define.

**Comment by ruanjiashing** [comment]
> You can open an issue in their repo for changing the default and definitely can send a PR by clicking "edit" in this for and add the OrangeC define.

Done.
