### ISSUE TITLE
Import library?

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#755]
I don't know the mechanic how OrangeC links with Windows' DLLs like user32.dll, shlwapi.dll or advapi32.dll. On Pelles C and MinGW there a import libraries for them shipped as part of the compiler distribution. Import library has the same extension as static library. On Pelles C, they are .lib files on `C:\Program Files\PellesC\Lib\Win` or `C:\Program Files\PellesC\Lib\Win64`. On MinGW they are .a files on `mingw64\x86_64-w64-mingw32\lib`. On OrangeC, it seems static library has the extension .l, so I think if import library is available they should have .l extension too. But I can't find any of them on OrangeC distribution. So how OrangeC actually link with Windows' DLLs? Does it support import library or not? Does it generate import library on the fly when it's needed? How could I generate import library from a DLL manually if I wanted? Thanks.

**Comment by GitMensch** [comment]
> Does it generate import library on the fly when it's needed?

That would be very useful. Last time I've checked only Mingw's GCC had that feature (you can directly link against a given dll).
I totally would like to be able to do the same with occ.

> How could I generate import library from a DLL manually if I wanted?

Use oimplib: https://github.com/LADSoft/OrangeC/blob/master/doc/general/OImpLib.md

**Comment by LADSoft** [comment]
Normally you don't have to deal with import libraries for windows stuff because occ ships with a default import library 'climp.l' that has most of the windows dll libraries in it.   But if you want to work with a library for your own dll you can use oimplib as @GitMensch suggested.  Currently, occ doesn't link against DLLs directly, but there is an issue #661 that asks for the functionality of auto-generating an import library when you attempt to link against a dll.    I guess I could fast track it.

**Comment by GitMensch** [comment]
> Currently, occ doesn't link against DLLs directly, but there is an issue https://github.com/LADSoft/OrangeC/issues/661 that asks for the functionality of auto-generating an import library when you attempt to link against a dll. I guess I could fast track it.

Actually that issue was closed by https://github.com/LADSoft/OrangeC/commit/3ea01281370c75913bfc44760276a6f6e2d1b506, so we only remembered it wrong and occ can be passed a DLL now. Or did I miss something?
