### ISSUE TITLE
Is it possible to link with static library compiled by other compilers?

### ISSUE THREAD

**Issue by ruanjiashing** [LADSoft/OrangeC#759]
I mean static library compiled by MSVC and Pelles C (.lib extension) and static library compiled by MinGW (.a extension). And as import library also has the same extension as static library, is it possible to link with import library generated by other compilers too? Thanks.

**Comment by LADSoft** [comment]
well beyond being able to link against CRTDLL.DLL and MSVCRT.DLL I haven't tried linking against other people's libraries.   For C language it may be possible but would take a bit of work to work out how to do the initialization.    HOWEVER,   there is a program I wrote, coff2ieee.exe, which attempts to convert MSVC libraries to occ libraries.    It has been used successfully in the past.   But it would only work with C language libraries due to disparities in function naming, and in the function call argument lists (MSVC passes the this pointer in ecx whereas occ currently does not)

**Comment by GitMensch** [comment]
I've forgot about that, just dropping the reference link: https://github.com/LADSoft/OrangeC/blob/master/doc/general/Coff2IEEE.md which also has the note about "doesn't work with C++ libraries".
