### ISSUE TITLE
Missing *intrin* headers

### ISSUE THREAD

**Issue by iahun** [LADSoft/OrangeC#763]
Code failed to compile because missing of them. Pelles C ships with various `*intrin*` headers, OrangeC should be, too.

**Comment by chuggafan** [comment]
the `<intrin>` headers are MSVC-specific, while it would be a good idea for us to ship them, at the moment missing 99.9999% of the intrinsics they would be providing it would do near-nothing.

**Comment by iahun** [comment]
> the `<intrin>` headers are MSVC-specific, while it would be a good idea for us to ship them, at the moment missing 99.9999% of the intrinsics they would be providing it would do near-nothing.

The code is expecting the present of them. It check for each C compiler and include the corresponding header. e.g: if Pelles C then it's intrin.h, if LCC then it's intrinsics.h, if Borland C then it's mmintrin.h, if it's GCC or Clang (not MSVC) then it's x86intrin.h and finally if it's MSVC then intrin.h.

**Comment by chuggafan** [comment]
My point is that the code would fail to compile even without it since #304 needs to be completed first. While it would be great to also support more builtins rightnow there's a full compiler rebuild for internals going on and that's probably the biggest priority because it will fix huge amounts of issues with speed so we don't run into the 1.5 hour limit on AppVeyor.

**Comment by iahun** [comment]
Understand.

**Comment by LADSoft** [comment]
that's probably the biggest priority because it will fix huge amounts of issues with speed

sigh.  I had been slowly pulling the times down...   the normal builds were down to about an hour and five minutes and most of the builds were actually completing (other than the libcxx tests which I haven't addressed yet).   While it is hard to tell, I'm thinking the new windows headers blew that out of the water by adding 10-15 minutes to the build time, and some things don't finish again...

I definitely see orange C building slower on my own computer now too...   it is especially noticeable if I watch the runtime library build...

I'm thinking I should check if there is a 'lean and mean' define for this set of headers lol...
