### ISSUE TITLE
Include directories not taken into account?

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#79]
Using the setup given in https://github.com/LADSoft/OrangeC/issues/76 ocide shows:

~~~
;============ Building Project libcob ============
;============ Compiling call.c ============
Error( 34)    C:\dev\gnucobol-2.2\libcob\call.c(115):  Cannot open include file "libcob.h" in function lt_dlsym
~~~

Despite the issue that the include was not done in function  `lt_dlsym` (resetting the function name for messages after the function definition is ended is missing) it seems to show that the include directories somehow don't apply here.

Additional include paths are set to `..;..\build_windows` and libcob.h is available as C:\dev\gnucobol-2.2\libcob.h.
Note: it doesn't matter if the include path setting is relative as in the setting above or absolute to `C:\dev\gnucobol-2.2;C:\dev\gnucobol-2.2\build_windows`.

side note: I'll be away for the next days and won't respond to any issues.

**Comment by LADSoft** [comment]
there was an issue with \ before the ending quote, which I've resolved, but beyond that there is a subtle problem.   When using the IDE the paths the compiler will use are relative to the project file, because they have to be relative to something and there is no other stable point of reference.   Because you didn't put the project file in with the sources, the include paths based on where the project file is should be: ..\..;..\

**Comment by GitMensch** [comment]
Hm, it still doesn't work when using the absolute path `C:\dev\gnucobol-2.2;C:\dev\gnucobol-2.2\build_windows`:

~~~
;============ Compiling call.c ============
Error( 34)    C:\dev\gnucobol-2.2\libcob\call.c(115):  Cannot open include file "libcob.h" in function lt_dlsym
~~~

Do I miss something or should this work?

**Comment by LADSoft** [comment]
i'm not sure, it seems to work here.  Did you set the include paths on the project or on the file?   Are you building in debug or in release?

**Comment by GitMensch** [comment]
... or not...
I'm really confused.

Given the layout 

x:\project                     --> headers here
x:\project\source1
x:\project\source2
x:\project\build             --> more headers here
x:\project\build\ocide   --> project.cwa and source1.exe.cpj and source2.exe.cpj here

How should the additional include paths be set?

I've tried (on project.cwa):
* $(PROJECTDIR)\..\..;$(PROJECTDIR)\..
* ..;..\..
* x:\project;x:\project\build

None of these worked ?!?

**Comment by LADSoft** [comment]
it does work...  you should use ..\\..;..   although I agree I had problems too at first :)

when I tried to duplicate this issue I forgot to uncheck the 'create new directory for project' checkbox and so it created a nested directory...   under THAT scheme I would have had to use ..\\..\\..;..\\.. to make it work.

Because all this is confusing under your use case I did some checking as to whether the compiler should look for include directories relative to where the compiler finds the source file...   but the microsoft compilers at least take it relative to the CWD when the compiler is invoked (which OCIDE sets to where the project file is) so the behavior is going to stay...

**Comment by GitMensch** [comment]
I know see it: the additional compiler include paths that are specified on the default.cwa level seem to do nothing. If I remove them and add the exact same values (full paths) to the project properties it works.

Where is the bug? Shouldn't the cwa properties have these options or should the be inherited for the projects (which I assume)?
