### ISSUE TITLE
Bug with the preprocessor

### ISSUE THREAD

**Issue by hgntn** [LADSoft/OrangeC#798]
Normally Objective C code should be put on .m source file but sometimes people also put Objective C code on .c source file like this:

```
#ifdef __OBJC__
// Objective C code
#endif
```

I confirmed that `__OBJC__` is not defined on OrangeC. But why this piece of code triggered an error?

```
#ifdef __OBJC__
#import <Cocoa/Cocoa.h>
#else
#include <windows.h>
#endif
```

The error is:

```
Error test.c(2): Invalid preprocessor directive
1 Errors
```

**Comment by LADSoft** [comment]
Hm generally this works, as I don't think it will evaluate #error or #warning or other preprocessor things while in the empty part of an if statement...   maybe it is just an issue with unknown preprocessor directives....    will look at it soon...

**Comment by chuggafan** [comment]
It's an issue with the evaluation of any preprocessor command during the execution of context as it looks to see if there's any valid preprocessor directives while doing the processing in order to see when the end of the ifdefs are, it's line 196(?) of preprocessor.cpp

The fix is simple enough I'll add it to my latest pull: just make an include.Skipping check first before erroring on line 250 of the same file.

**Comment by LADSoft** [comment]
ok thank you!

**Comment by LADSoft** [comment]
@hgntn 

i still can't duplicate the bug with omake crashing, what os/osversion are you using?   And what command shell?

Thanks

**Comment by hgntn** [comment]
> @hgntn
> 
> i still can't duplicate the bug with omake crashing, what os/osversion are you using? And what command shell?
> 
> Thanks

Also Windows 8.1 64 bit like @tn1997tn with Command Prompt shell, an additional information is I have not updated Windows since I bought this PC (I disabled Windows Updates).
