### ISSUE TITLE
How broken is the support of Orange C for DOS?

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#828]
From what this page said: https://ladsoft.tripod.com/orange_c_compiler.html

Please correct me if I am wrong. It seems Orange C indeed has no support for DOS at all. It's using a DOS extender with Windows API emulation to run the unmodified binaries compiled for Win32. If it is really the case, then what about just removing support for DOS altogether? DOS people has better compilers to use, e.g: https://github.com/tkchia/build-ia16

**Comment by LADSoft** [comment]
well the support for dos is broken ever since I started using shared memory regions, I haven't fixed it yet because noone seems to want it aside from @GitMensch.   But aside from running as win32 executables under dos, it has a *lot* of support for various dos extenders so you can run 32-bit DOS code without resorting to windows emulation if you want.

But I will take it under advisement that maybe I should just delete the DOS version since noone seems to want it lol...
