### ISSUE TITLE
Orange C and `./configure`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#831]
How good are the emulators for GCC and binutils? Did anyone tried to use Orange C with GNU Autotools `./configure` script?

**Comment by chuggafan** [comment]
What emulators are you talking about?

autoconf is also an entirely separate thing (and automake and m4, etc.) which is more to do with `./configure`, are we talking specific libraries? I know there's work to support autoconf in the context of GNU Cobol but I'm not sure if that's still failing in any way, can you be a lot more specific?

**Comment by LADSoft** [comment]
@GitMensch had me working on several projects, with autoconf.   They don't need the wrappers; you can set up the configuration with occ natively (we used msys2).   It isn't perfect at this point, but we've addressed a *lot* of problems by fixing bugs and adding various gcc-compatible command line switches.   I think @GitMensch may have submitted a change to something broken in one of the autoconf scripts as well, not sure on that.

Last I checked gnu cobol compiled but there was a bug in the gnucobol scripts where it wouldn't link.   But I could copy a couple of files around and restart the build then it would link and we'd have a running gnucobol.   

We've also  successfully run the gnucobol tests and that was another source for finding bugs.   I think I was asked to try again with gnu cobol rc3 but I waited around a few weeks and it never materialized in subversion so I'm still waiting.

other things we've checked with autoconf were similar at the time I checked them - you can get a long way through the build but may have to do just a little of hand-massaging to complete it.   But I did complete several projects successfully that way.

This hasn't been a high priority for me because @GitMensch is the only one who's been interested so far lol...    but there IS an issue for me to revisit it and see where we are at some point in the future.    It is quite possible that autoconf will work more generally because in the meantime since I last checked we've added a lot of gcc-compatible switches.

**Comment by iahunq** [comment]
So, how do you make it work? Adding Orange C to MSYS2's PATH and just running `./configure`?

**Comment by GitMensch** [comment]
Correct, adding the OrangeC bin folder, then run configure passing the computer and told name using the standard approach like

    ../configure CC="occ --nologo" MAKE=omake ...

Have a look at the GnuCOBOL test bed issue, when interested. Of course, for the compile/link part neither make not get need to be set, that's just an additional test for those.

**Comment by iahunq** [comment]
The configure script does more things than you think. You should have a closer look at what it printed on the screen and you should inspect `config.log`, too. This will reveal a lot of insights. The configure script has no idea what Orange C is. It expects a GNU-like environment and it thinks Orange C to be something GCC compatible and it's still using GNU binutils that is incompatible with Orange C for almost everything Orange C not yet provided emulators for, e.g: `nm`, `dlltool`,... It's not for no reasons LLVM provided wrappers for LLVM tools to emulate GNU binutils.

**Comment by iahunq** [comment]
Btw, Orange C is a 32 bit only compiler. I think we should use the MINGW32 environment of MSYS2 instead of MINGW64. Did any of you notice when you run the configure script it still detect the host system type and build system type as `x86_64-w64-mingw32`?

**Comment by iahunq** [comment]
@GitMensch Perhaps you are lucky with GnuCOBOL. Try the FOX Toolkit's configure script. It will not be that easy.

**Comment by GitMensch** [comment]
@iahunq maybe you have not used the search function https://github.com/LADSoft/OrangeC/issues?q=is%3Aissue+is%3Aopen+testbed leading to https://github.com/LADSoft/OrangeC/issues/168?

This sets most of the tools you've mentioned (they even work without wrappers):

```sh
../configure "CC=occ --nologo" "MAKE=omake -w" "LD=olink --nologo" "CPP=ocpp -I\orangec\include --nologo" "CXX=occ --nologo" "CXXCPP=ocpp -I\orangec\include --nologo" "GREP=grep" "EGREP=ogrep" "NM=onm --nologo" "CPP_FOR_BUILD=ocpp --nologo" CC_FOR_BUILD="occ --nologo" AR="olib --nologo" \
	RANLIB="echo no ranlib" STRIP="echo no strip" \
	CPPFLAGS="-I$PWD/../config -I$PWD -D__GMP_LIBGMP_DLL -DPDC_DLL_BUILD \
	LDFLAGS="-L$PWD" --disable-static --enable-shared
```

Note: in this case the configure directory has include files and link libraries generated by`for lib in *.dll; do (echo converting $lib...; oimplib -C $(echo $lib | cut -d. -f1).l $lib); done`.

Obviously neither ogrep nor omake are necessary, those were just additional tests for those specific tools.
