### ISSUE TITLE
gccocc should ignore any unknown `-Wno-warning`

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OrangeC#843]
Just as GCC does. The benefit on the GCC side is that you can suppress warnings and an older version of the compiler won't complain that it doesn't have the warnings you suppress in the first place. I'd suggest that occ, if not doing the same currently, would be similar.

This actually "fixes" all of the recent "does not understand -Wno-xyz" issues.

**Comment by GitMensch** [comment]
It is likely reasonable - for the wrapper - to ignore any unknown `-Wxyz`, then only hand-match the warnings we do know that have a pendant in occ.

**Comment by LADSoft** [comment]
it may be beyond the scope of what I want to do, to go through every warning GCC has and map it to an OCC warning.   I will research how many there are and see.    But certainly I can ignore anything that comes with a -W switch so I will.

I'm going to go through and close all the  other issues related to -Wxxxxxxxxx since this supercedes them, please don't make any more :smile:

**Comment by LADSoft** [comment]
i looked through the gcc warnings list and then created #851 as it may be useful to implement some of them later.   For this issue I'm going to implement the following and then make sure that anything else that follows "-W" is ignored...

-fmax-errors=n
-w 
-Werror
-Werror=
-Wfatal-errors 
-pedantic ignore
-pedantic-errors ignore

-Wall
-Wextra
