### ISSUE TITLE
gccocc doesn't understand `-fpermissive`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#892]

**Comment by chuggafan** [comment]
I am once again asking for you to make one single issue about deficiencies you see in gccocc and just edit different "It doesn't conform to X" thing to that issue.

I am getting extensively annoyed at looking at my notifications to see around 60 or 70 different notifications (and emails!) that are all relatively related and shouldn't be a separate issue.

Please do this in the future, thank you.

**Comment by iahunq** [comment]
I understand your inconvenience, but I have my own reasons to submit separate issues. As you can see, these issues are indeed not related to each other. Of course, I could try to create a mega issue to keep track of all of the unsupported switches, but this issue, as its name `mega` suggests, will be quite large and hard to keep track of which were handled and which were not. The advantage of multiple separate issues is that you could handle each of them separately. The only fault of mine is that I submitted too many issues at the same time. Sorry.

**Comment by LADSoft** [comment]
@iahunq:

So I have to think about all these issues you wrote.    When I first put in gccocc, it was never with the intent for it to be a drop-in replacement for gcc.    The idea, as proposed by GitMensch, was to have a basic way for people who didn't want to learn the OrangeC command line parameters to be able to do something somewhat familiar.   Not so much to be able to use every gcc command line known to man.    Along those lines, I think that at least some of the issues you've brought up have merit and could apply (for example -m32 and -m64 would be good to add I think even though technically they won't apply until I make a 64-bit version of the compiler)   but on the other hand it would be misleading to add things like -pthreads because OrangeC doesn't support it directly and I don't intend for it to.

**Comment by iahunq** [comment]
These are the most commonly used switches of GCC, not every switches of GCC known to man. My idea is they should be handled. The switches that are irrelevant to Orange C should be ignored. The switches that Orange C has something equivalent should be mapped.

**Comment by LADSoft** [comment]
@iahunq, 

I added all the switches you didn't close, but, don't have time tonite to finish testing it.    Will finish it tomorrow and do another push...

**Comment by LADSoft** [comment]
0e43f6ee8a154a5373ce84804fea3e5ecc3609a6
