### ISSUE TITLE
shouldn't alloca be a macro?

### ISSUE THREAD

**Issue by lionfaith** [LADSoft/OrangeC#9]
Hello!
I'm not sure about this one. But I discovered that SDL 1.2.12, in SDL_stdinc.h, tests the presence of alloca function with `#if defined(HAVE_ALLOCA) && !defined(alloca)` as if alloca were a macro. But it doesn't work with occ which doesn't see it that way. I had to hack the header to specifically manage OrangeC case. I'm not sure if it is really a bug though.

**Comment by LADSoft** [comment]
Hi Lionfaith,

I too am unsure whether to classify it as a 'bug' since alloca isn't 
part of the C standard :).   However, as there is a precedent for how it 
is handled I've adjusted Orange C to do it the same way.   Now, if you 
want alloca or _alloca to be supported include "malloc.h" and it will 
define them as macros.

David
lionfaith wrote:

**Comment by lionfaith** [comment]
As I can read it in SDL_stdinc.h, it is the way msvc, borland and watcom does it. (but Gnu has `__builtin_alloca`, digital mars puts alloca in stdlib.h, AIX asks for a `#pragma alloca` and MRC asks for declaration `void *alloca (unsigned);`). Too bad it is not standardised, at least with a standardised way of knowing if alloca is there and how to "activate" it.
Thanks for your work!

**Comment by LADSoft** [comment]
you're welcome.  mingw/gnu actually has alloca defined as macros in malloc.h, they reference the __builtin_alloca function.    I chose to do it the same way :)
