### ISSUE TITLE
MinGW-w64 also has `unistd.h`

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#925]
You could check this even with your standalone MinGW-w64 8.1.0. `HAVE_UNISTD_H` is not equivalent to `__linux__`. Please review your commits.

**Comment by LADSoft** [comment]
that was kind of the point...    HAVE_UNISTD_H is defined in gcc-linux.mak.

I didn't want this linux-specific since it can apply to builds in the msys-2 environment as well...   and at the time I made the change I was building the compiler in the msys2 environment, with COMPILER=gcc-linux....   so that took away the linux dependency and made things more generic...

**Comment by iahunq** [comment]
Then how do you handle Linux-specific code now?

**Comment by GitMensch** [comment]
Commonly it is enough to just use

```c
#ifndef _WIN32
```

(note `__CYGWIN__` does not define that)
