### ISSUE TITLE
All recent builds on AppVeyor CI were cancelled 

### ISSUE THREAD

**Issue by iahunq** [LADSoft/OrangeC#927]
They took longer than what the plan allowed. What caused this increasing in build time recently? Btw, should I get the latest build from Github Action now?

**Comment by LADSoft** [comment]
AFAIK the problem is @chuggafan is doing checkins on #810.   you can tell by looking at the information about the checkin; the ones' I've been checking in are on 'master' and @chuggafans are on a branch.

You should be able to use the build on github action, just be aware there is a slight difference from appveyor; on appveyor the builds are orangec compiled with itself whereas the builds on github action are orange c compiled with msvc.    Usually that doesn't make much difference, although to be fair the github action builds are a little faster to complete, and run faster as well...
